### ISSUE TITLE
Freezing object after adding to WeakMap in IE11

### ISSUE THREAD

**Issue by smares** [zloirock/core-js#384] opened 2018-03-02 14:57 UTC
I just stumbled upon a problem that affects only IE 11. It does not happen with IE 9, IE 10, Edge, Firefox or Chrome:

```javascript
var wm = new WeakMap()
var key = {}

wm.set(key, 'foo')
console.log(wm.get(key)) // yield: 'foo'
Object.freeze(key)
console.log(wm.get(key)) // yield: 'undefined' for ie11 using polyfill | 'foo' for ie11 without polyfill
```

The latter case should be correct, `wm.get(key)` after calling `Object.freeze(key)` should return `foo` as it does in IE 9 with polyfill, IE 10 with polyfill, IE 11 without polyfill, Edge without polyfill, Chrome without polyfill and Firefox without polyfill.

**Comment by zloirock** [comment] 2018-03-02 17:33
You have confused the cause and effect. Without a polyfill, IE11 `WeakMap` can't work with frozen keys completely. `core-js` [adds a fallback](https://github.com/zloirock/core-js/blob/master/modules/es6.weak-map.js#L41-L59) and it [includes mutation objects in `Object.freeze`](https://github.com/zloirock/core-js/blob/master/modules/_meta.js#L42-L46). But this fix does not cover the case in your example, so yes, it can be marked as a bug.

**Comment by zloirock** [comment] 2018-03-25 19:54
Fixed in [`v3` branch](https://github.com/zloirock/core-js/pull/325).

**Closed by zloirock** 2018-03-25 19:54 UTC
Labels: bug, es6, ie
