### ISSUE TITLE
IE 11 issue - "Access Denied" in getOwnPropertyNames in modules/_object-gopn-ext.js

### ISSUE THREAD

**Issue by doctorssm** [zloirock/core-js#417] opened 2018-08-03 13:37 UTC
In IE11, getOwnPropetyNames throws an "Access Denied" error in modules/_object-gopn-ext.js

![2018-08-03_1636](https://user-images.githubusercontent.com/10260908/43645733-759e138a-973b-11e8-8d2a-adf5aa7319a7.png)

**Comment by djskinner** [comment] 2018-08-06 12:07
I am also seeing this in IE 11. Will report back if I can glean any further info.

**Comment by zloirock** [comment] 2018-08-27 18:50
Please, add a reproducible example. As you can see, this line in a `try` block for preventing this error.

**Comment by zloirock** [comment] 2018-09-12 08:28
Closed as `can't reproduce`.

**Closed by zloirock** 2018-09-12 08:28 UTC
Labels: can't reproduce

**Comment by djskinner** [comment] 2018-09-12 12:28
FWIW for me this was related to the use of iframes on IE11. Specifically I had to get rid of any references to iframe windows before they were unloaded from the page.
