### ISSUE TITLE
IE Bug: Array.prototype.toString: 'this' is null or undefined

### ISSUE THREAD

**Issue by Twisterking** [zloirock/core-js#312] opened 2017-06-25 21:09 UTC
[For more details, please check HERE](https://forums.meteor.com/t/ie-10-bug-uint8clampedarray-is-undefined/37493)

```
Array.prototype.toString: 'this' is null or undefined
```

This error appears when I just enter `Uint8Array` in the IE10 JS console. according to the IE debugger, the error originates from my Meteor `modules.js` file and the linenumber leads to core-js' [`_ctx.js`](https://github.com/zloirock/core-js/blob/master/modules/_ctx.js) file.

Any ideas on this? I really don't know whose fault this is ... babel, core-js, meteor ... I hope someone can help get me on the right track as I desperately need my Meteor app to work on IE10 and 11!

**Comment by zloirock** [comment] 2017-07-26 19:18
Seems a duplicate of #300.

**Closed by zloirock** 2017-07-26 19:18 UTC
