### ISSUE TITLE
Since 3.4.5: Android 4.4 device throws TypeError on load

### ISSUE THREAD

**Issue by fdc-viktor-luft** [zloirock/core-js#720] opened 2019-12-06 13:22 UTC
I want to report a bug, that I encountered recently when testing my application on an eInk-Reader-Device which runs basically like some Android 4.4 device.

I was able to detect that the issue belongs to **core-js@3.4.5**. Everything works with **core-js@3.4.4** but all later versions of **core-js** stopped working.

The stack trace of the error might be partially helpful:
```
TypeError: Cannot convert undefined or null to object
  at hasOwnProperty (native)
  at b.exports (...)
  at b.exports.exportTypedArrayMethod (...)
  at Object.<anonymous> (...)
```

Sadly I have no clue why the issue occurs. I tried to understand what happened within the 6 commits from version 3.4.4 to 3.4.5, but could not catch up quickly enough.

Please help me to resolve this issue since I want to keep the `core-js` dependency always up-to-date.

I'm willing to test all patches/fixes on the device as soon as possible. Please tell me if you need any additional information. Thank you! :+1:

**Comment by zloirock** [comment] 2019-12-06 13:37
I don't see any [changes between `3.4.4` and `3.4.5` ](https://github.com/zloirock/core-js/compare/v3.4.4...v3.4.5) which can affect it.

**Comment by zloirock** [comment] 2019-12-06 13:38
It can be related to #648.

**Comment by fdc-viktor-luft** [comment] 2019-12-06 14:11
Issue #648 seems to fit quite well. We're using create-react-app too. Sorry for creating a new issue.

**Comment by zloirock** [comment] 2019-12-07 00:12
(all tests passed on the Android 4.4 emulator)
![Снимок экрана 2019-12-07 в 06 47 34](https://user-images.githubusercontent.com/2213682/70364089-a8513000-18bd-11ea-80d4-ab39372b0c05.png)

**Comment by fdc-viktor-luft** [comment] 2019-12-09 08:31
Hi @zloirock 

I was able to build some application where you can reproduce the problem. 

Repo: https://github.com/fdc-viktor-luft/cra-test
Hosted: https://fdc-viktor-luft.github.io/cra-test/ (you should see a success prompt and the React logo - if it fails, you should the stack trace in some prompt)

While building this example I had the following insights:

When using `create-react-app` initial setup and adding the two lines
```ts
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```
to the `index.tsx` everything works with `core-js@3.4.5`. But after changing the Minimizer from `terser-webpack-plugin` to `webpack-closure-compiler` (see `config-overrides.js`) the loading of the app fails. This is currently hosted example. The prompted stack trace is similar as mentioned above.

**But** the combination of  `create-react-app`, `webpack-closure-compiler` and `core-js@3.4.4` works perfectly.

Hopefully the hosted example can help you, to help me :grinning: 

Btw. we have to use the closure comiler because we need ECMAScript 3 for some Android 2 devices. :sob:

**Comment by zloirock** [comment] 2020-01-10 15:59
A will not have a chance to explore it in Android 4.4 shortly, so marked as `help wanted`.

**Comment by davidsteinberger** [comment] 2020-03-28 23:04
I just ran into a similar issue. Debugged it for some time to find out that it was caused by a combination of webpack and babel (w/ core-js polyfills). Fixed it as described in https://github.com/zloirock/core-js/issues/743#issuecomment-572074215.

**Comment by fdc-viktor-luft** [comment] 2020-03-30 06:09
Thanks for your suggestion. I will try to fix it as soon as I'm able to get my hands on that Android device again. But this can take some time, since I'm working currently from home like probably most of you do 😉

**Comment by zloirock** [comment] 2021-04-07 19:02
It looks like that the reason has been figured out.

**Closed by zloirock** 2021-04-07 19:02 UTC
Labels: can't reproduce, help wanted

**Comment by fdc-viktor-luft** [comment] 2021-04-08 06:57
@magWagner If you're still effected by this issue. Here you can probably find a solution following the above suggestion.
