### ISSUE TITLE
Error: Uncaught (in promise): Error: Out of stack space when using with Angular in IE11

### ISSUE THREAD

**Issue by vanelizarov** [zloirock/core-js#545] opened 2019-05-13 17:07 UTC
Suddenly I've started seeing this error in IE's console:
```
Error: Uncaught (in promise): Error: Out of stack space
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
   at $set (http://localhost:4200/polyfills.js:6755:7)
```

I'm using the following polyfills:
```javascript
import 'core-js/es6/symbol'
import 'core-js/es6/object'
import 'core-js/es6/function'
import 'core-js/es6/parse-int'
import 'core-js/es6/parse-float'
import 'core-js/es6/number'
import 'core-js/es6/math'
import 'core-js/es6/string'
import 'core-js/es6/date'
import 'core-js/es6/array'
import 'core-js/es6/regexp'
import 'core-js/es6/map'
import 'core-js/es6/weak-map'
import 'core-js/es6/set'
import 'core-js/es6/weak-set'
import 'core-js/es7/array'
import 'core-js/es6/reflect'
```

The problem is in `symbol` polyfill, here's the line 6755 in compiled file:
```javascript
if (this === ObjectProto) $set.call(OPSymbols, value);
```

Usage of `Symbol` function (actually it is used by one of the libs, [`comlinkjs`](https://www.npmjs.com/package/comlinkjs)):
```javascript
var proxyMarker = Symbol("Comlink.proxy");
var createEndpoint = Symbol("Comlink.endpoint");
```

**Comment by zloirock** [comment] 2019-05-13 17:09
Could you add a reproducible example?

**Comment by vanelizarov** [comment] 2019-05-14 12:35
@zloirock yeah, I've created a repo with demo app:
https://github.com/vanelizarov/core-js-ie11-symbol-error-demo

**Comment by zloirock** [comment] 2019-05-15 20:03
That looks like a duplicate of #260.

**Comment by zloirock** [comment] 2019-05-19 10:50
Closed since it's [documented](https://github.com/zloirock/core-js#caveats-when-using-symbol-polyfill) for a long time:

> Some problems possible with environment exotic objects

If you know a simple way of fixing this problem feel free to propose it.

**Closed by zloirock** 2019-05-19 10:50 UTC

**Comment by vanelizarov** [comment] 2019-05-19 17:33
@zloirock unfortunately, I could not resolve this issue. I’ve tried `Symbol.useSimple()`, but it did not help. I think we can stop here and close issue
