### ISSUE TITLE
"TypeError: Cannot redefine property: push" on Chrome 113 on Mac OS X

### ISSUE THREAD

**Issue by MaxHatfull** [zloirock/core-js#1262] opened 2023-06-15 09:38 UTC
Since upgrading core-js from version 3.30.2 -> 3.31.0 we've noticed the exception "TypeError: Cannot redefine property: push" coming from core-js. Our error reporting says this has only been seen on Chrome 113 on Mac OS X.

Stack trace: 

```
File ../../../../node_modules/core-js/internals/define-built-in.js:20:31 in [anonymous]
else definePropertyModule.f(O, key, {
File ../../../../node_modules/core-js/internals/export.js:52:5 in [anonymous]
defineBuiltIn(target, key, sourceProperty, options);
File ../../../../node_modules/core-js/modules/es.array.push.js:28:1 in [anonymous]
$({ target: 'Array', proto: true, arity: 1, forced: FORCED }, {
```

If there's any more information we can provide, we'll try our best!

**Comment by zloirock** [comment] 2023-06-15 10:00
Could you add a reproducible example? It looks like a broken environment where built-ins are frozen or at least `Array#push` made is non-configurable.

**Comment by romainmenke** [comment] 2023-06-18 21:54
We see the same error :

```
TypeError Cannot redefine property: push 
    /node_modules/core-js/internals/define-built-in.js:20:30 e.exports
    /node_modules/core-js/internals/export.js:52:4 e.exports
    /node_modules/core-js/modules/es.array.push.js:28 8496
    webpack/bootstrap:19:31 __webpack_require__
    https://wp-static.assets.sh/ctTVRGVHRyyEofVd8tblYYB_67UuSVZVQ4QS1mcM6cc/assets/js/app.s2023-0.min.js:1:65432 
    https://wp-static.assets.sh/ctTVRGVHRyyEofVd8tblYYB_67UuSVZVQ4QS1mcM6cc/assets/js/app.s2023-0.min.js:1:113052 
    https://wp-static.assets.sh/ctTVRGVHRyyEofVd8tblYYB_67UuSVZVQ4QS1mcM6cc/assets/js/app.s2023-0.min.js:1:113056 
```

All seemingly coming from the same user agent string :

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

But the number of reports is way to low to be actual Chrome 113 :

<img width="288" alt="Screenshot 2023-06-18 at 23 46 22" src="https://github.com/zloirock/core-js/assets/11521496/5f245911-04bf-4085-8038-734e7a8c1e7f">

Most we've seen is 5 error reports in a 12 hour window.
In the same window we've had ±120.000 requests, of which a certain percentage will have been for Chrome 113. This percentage will be higher than `0.000041666666667%`

> It looks like a broken environment where built-ins are frozen or at least Array#push made non-configurable.

So yeah, seems that way to us :)

**Comment by zloirock** [comment] 2023-06-27 00:44
Closing. It seems something like a web crawler with broken js env.

**Closed by zloirock** 2023-06-27 00:44 UTC
Labels: can't reproduce
