### ISSUE TITLE
Promise polyfill overriding problem

### ISSUE THREAD

**Issue by slawwan** [zloirock/core-js#332] opened 2017-08-24 14:44 UTC
I have unexpected for me behavior in Firefox 55.0.2 64bit
![image](https://user-images.githubusercontent.com/5162965/29670846-6573b1e8-8901-11e7-8ac9-40c51ac7ade0.png)

I've found similar issue #264 and explanations in #191 and I saw other issues and discussions
So it is a problem not only for me

I understand that main aim of overriding existing Promise is to fix its bugs.
But there is a problem if some code, in my example native code, works with native Promise
So when I work with fetch, all chain of `then` it is a chain of native Promise, not overridden, and it is produce other bugs and problems and it is not obvious. It means that polyfill does not fix problems of native implementation.

Maybe this functionality should be optional?
Or it may be better to abandon this functionality?

**Comment by zloirock** [comment] 2017-08-24 15:08
It's a duplicate of #178, see my answer: https://github.com/zloirock/core-js/issues/178#issuecomment-192081350

**Comment by zloirock** [comment] 2017-08-24 15:12
Seems you propose something like #283, so I'll close it.

**Closed by zloirock** 2017-08-24 15:12 UTC
