### ISSUE TITLE
core-js/stable/promise on Android 4.4

### ISSUE THREAD

**Issue by brandonburkett** [zloirock/core-js#659] opened 2019-10-08 00:56 UTC
Hi,

I was doing some cross browser testing after updating dependencies and I noticed that `core-js/stable/promise` was breaking Android 4.4 / Samsung browser.

It worked great with 3.1.4, but after upgrading to 3.2.0 or 3.2.1, code seems to halt at the import.

Note I am testing through browser stack, but here is how to replicate.  Apologies that I do not have a physical device nor can I get the actual JS error because browser stack doesn't have a debugger for the Samsung browser like it does for chrome on Android.

-----
**3.1.4**
```javascript
// app.js

import 'core-js/features/array/from'
import 'core-js/features/array/includes'
import 'core-js/features/object/assign'
import 'core-js/features/dom-collections/iterator'
import 'core-js/stable/promise'
import 'core-js/modules/es.array.iterator'
import 'core-js/features/number'
import 'core-js/features/string/includes'
import 'core-js/features/symbol'
import 'core-js/features/symbol/async-iterator'
import 'core-js/web/dom-collections'

window.alert('got here') // my only way to debug with this browser in browser stack, but does execute

```

**3.2.0+**
```javascript
// app.js

import 'core-js/features/array/from'
import 'core-js/features/array/includes'
import 'core-js/features/object/assign'
import 'core-js/features/dom-collections/iterator'
import 'core-js/stable/promise'
import 'core-js/modules/es.array.iterator'
import 'core-js/features/number'
import 'core-js/features/string/includes'
import 'core-js/features/symbol'
import 'core-js/features/symbol/async-iterator'
import 'core-js/web/dom-collections'

window.alert('got here') // does not ever execute unless I comment out import 'core-js/stable/promise' above

```

If I comment out `core-js/stable/promise`, I can see the alert.

----

Thanks
Brandon

**Comment by zloirock** [comment] 2019-10-08 04:59
If I understood correctly, it's a duplicate of #640, it fixed and a new release with this fix will be available in some days.

**Closed by zloirock** 2019-10-08 04:59 UTC

**Comment by brandonburkett** [comment] 2019-10-08 13:58
I missed that one when searching.  It's the same issue, thanks!
