### ISSUE TITLE
TypeError for Set polyfill on Chrome and Opera browsers on Windows OS

### ISSUE THREAD

**Issue by afr114** [zloirock/core-js#363] opened 2017-12-02 01:23 UTC
Having a weird issue when I upgraded to react 16, not sure if any one else has seen this.  I got the following exception error for windows OS on Chrome and Opera browsers```Uncaught TypeError: Cannot set property Set of [object Object] which has only a getter```

I imported the Set polyfill like so ```import 'core-js/es6/set';```

**Comment by loganfsmyth** [comment] 2017-12-02 01:50
Sounds like maybe something else loading on your page before core-js might be breaking things?

**Comment by afr114** [comment] 2017-12-02 02:10
@loganfsmyth if that were the case, why do you think it is happening in a windows OS and only in Chrome/Opera browsers?  I tried replicating that error through browserstack but couldn't not replicate it.  Although my bug monitoring app kept showing it happening.

**Comment by loganfsmyth** [comment] 2017-12-02 02:20
Yeah I don't know. Without a reproduction case it's hard to narrow it down. Perhaps there is some other logic on the page that only runs on Chrome for Windows?

**Comment by zloirock** [comment] 2017-12-08 18:17
Closed as `can't reproduce`. I'll reopen it after adding a reproducible example.

**Closed by zloirock** 2017-12-08 18:17 UTC
Labels: can't reproduce

**Comment by afr114** [comment] 2018-02-22 02:07
I wanted to circle back to this.   It turns out that we were adding a method to Array.Prototype that was clashing with core-js.
