### ISSUE TITLE
Unable to use in environment with csp due to unsafe-inline

### ISSUE THREAD

**Issue by Cwright017** [zloirock/core-js#274] opened 2017-01-25 14:24 UTC
We have a csp enabled on our project and it was failing on an old broser (the ps4 browser) due to core-js using a polyfill with iframes and inline script tags. Is there a way around this?

**Comment by zloirock** [comment] 2017-01-25 15:50
IIRC `core-js` have 3 places with possible CSP issues: `Function` constructor in global object detection, but it's used only in non-browser engines, `Function` constructor in `Function.prototype.bind` polyfill, but it's used only in IE8- and iframe with inline script tags for `Object.create` polyfill, but it's used only in IE8-, so in modern engines should no be CSP issues with `core-js`. I didn't test it in PS4 browser and I haven't PS4 at hand for say something about it.

**Comment by zloirock** [comment] 2017-12-08 19:59
Closed as `can't reproduce`. I don't see how it can break CSP in any engine.

**Closed by zloirock** 2017-12-08 19:59 UTC
Labels: can't reproduce
