### ISSUE TITLE
Missing compatibility data for `web.structured-clone`

### ISSUE THREAD

**Issue by wcauchois** [zloirock/core-js#1355] opened 2024-07-24 16:59 UTC
When I use the `core-js-compat` library to get information about `web.structured-clone`, it returns that it should always be polyfilled.

For example:

```js
const compat = require('core-js-compat')
const result = compat({
  targets: 'Chrome > 110', 
  modules: [                 
    /structured-clone/
  ],
  exclude: [],
  version: '3.27.1',   
  inverse: false,
})
console.log(result)
```

outputs

```
{
  list: [ 'web.structured-clone' ],
  targets: { 'web.structured-clone': { chrome: '111' } }
}
```

I would expect it to not be in the list, since this feature is fairly widely supported and 110 is a recent version of Chrome.

I'm not super familiar with core-js internals but I dug a bit and I found this portion of some compatibility table which seems commented out:

https://github.com/zloirock/core-js/blob/381182122fe63b4b4213c69ec3f6f69e2da857fe/packages/core-js-compat/src/data.mjs#L2678-L2684

is this a bug? And either way, would it be possible to correct the compatibility output in this case?

**Comment by zloirock** [comment] 2024-07-24 17:11
It's not a bug in the compat data, it's implementations issues. For example, `core-js` relies on proper error cloning semantics, https://github.com/whatwg/html/pull/5749, that's still not merged to the spec. It's missed in most engines, but available in some, like Firefox - but they have other issues. There were **very many** other issues in `structuredClone` / structured clone algorithm implementations, but most of them already fixed.

If the proper error cloning semantics will not be merged to the spec soon, most likely this requirement will be removed from the feature detection - but anyway not all actual implementations will be marked as proper.

**Comment by zloirock** [comment] 2024-07-24 17:21
If `structuredClone` is available natively and incorrect only in some minor moments, it's used in polyfill - just wrapped to fix those moments.

**Closed** 2024-07-24 17:21 UTC
Labels: question
