### ISSUE TITLE
symbol process throw error——Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by HannibalKcc** [zloirock/core-js#1292] opened 2023-09-24 09:57 UTC
version: core-js `3.32.2`

phone : `vivo X7Plus`
ua: `Mozilla/5.0 (Linux; Android 5.1.1; vivo X7Plus Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 KugouBrowser`

error source:
https://github.com/zloirock/core-js/blob/743a5adfd6574e70a65034facf7250a499c4f8d4/packages/core-js/internals/to-property-key.js#L9

in most of devices which i can find, only this device will throw error.

**Comment by zloirock** [comment] 2023-09-24 10:05
Please, add a reproducible example - without it, it is impossible to say something. I know about some such `Symbol` issues in such Chrome versions - but all of them are worked around.

**Comment by zloirock** [comment] 2023-09-30 21:46
Closed as `can't reproduce`.

As an option, it could be incorrect targets (for example, `es.symbol` is not injected) or a conflict with an alternative polyfill.

**Closed by zloirock** 2023-09-30 21:46 UTC
Labels: can't reproduce

**Comment by whyer11** [comment] 2024-05-14 01:47
> version: core-js `3.32.2`
> 
> phone : `vivo X7Plus` ua: `Mozilla/5.0 (Linux; Android 5.1.1; vivo X7Plus Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 KugouBrowser`
> 
> error source:
> 
> https://github.com/zloirock/core-js/blob/743a5adfd6574e70a65034facf7250a499c4f8d4/packages/core-js/internals/to-property-key.js#L9
> 
> in most of devices which i can find, only this device will throw error.

后来这个问题有解决吗？
