### ISSUE TITLE
"Attempting to configurable attribute of unconfigurable property."

### ISSUE THREAD

**Issue by SeanHayes** [zloirock/core-js#279] opened 2017-02-07 04:47 UTC
I'm using babel-polyfill, which I believe uses core-js. I'm seeing this error reported in some browsers (Safari <=7, Chrome 47, Nintendo Browser, Playstation Vita Browser):
"Attempting to configurable attribute of unconfigurable property."
I used this site to translate the line & col number:
https://raygun.com/sourcemaps
It says the error is happening in core-js/modules/es6.math.acosh.js?7396

I removed the Math polyfills since I didn't need them, but I still see the error in core-js/modules/_object-to-array.js?7d99 on line 4.

http://stackoverflow.com/questions/42121057/core-js-attempting-to-configurable-attribute-of-unconfigurable-property

**Comment by zloirock** [comment] 2017-07-26 19:12
I can't say anything without a reproducible example.

**Comment by zloirock** [comment] 2017-08-25 08:10
Closed as `can't reproduce`.

**Closed by zloirock** 2017-08-25 08:10 UTC
Labels: can't reproduce
