### ISSUE TITLE
Using Symbol under PhantomJS leads to error

### ISSUE THREAD

**Issue by rubenspgcavalcante** [zloirock/core-js#246] opened 2016-09-29 14:04 UTC
Hello! When I use the "core-js/es6/symbol" or the "babel-polyfill, a typechecking of the Symbol is throwing a exception: *(I'm using webpack)*

```javascript
	var isObject = __webpack_require__(13);
	module.exports = function (it) {
	  if (!isObject(it)) throw TypeError(it + ' is not an object!');
	  return it;
	};
```
When the code reach this module where has a check using the *isObject* function, it returns false the the *it* paramater is a Symbol. The PhantomJS output in a log of the **it** param and the evaluation of the **isObject** function:

```
PhantomJS 2.1.1 (Linux 0.0.0) LOG: _Symbol{}, false
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not an object!
``` 

Transpiling only a file like this, already makes PhantomJS throw the error:
```javascript
import "core-js/es6/symbol"; //A file only with the import is capable of cause the error
```

**Comment by zloirock** [comment] 2016-09-29 14:11
Looks like a duplicate of #189.

**Closed by zloirock** 2016-09-29 14:11 UTC
