### ISSUE TITLE
"Incompatible receiver, Map required" in React Native v0.57

### ISSUE THREAD

**Issue by gsklee** [zloirock/core-js#581] opened 2019-06-21 05:33 UTC
The JavaScriptCore for Android that came with React Native v0.57 does not support Symbols (https://github.com/facebook/react-native/issues/15902) so I tried to polyfill it:

```js
import 'core-js/features/symbol';
```

This will result in the following error:

![https://i.imgur.com/Or3cwU9.png](https://i.imgur.com/Or3cwU9.png)

Comments within that thread (https://github.com/facebook/react-native/issues/15902#issuecomment-375521246) were suggesting something like this:

```js
import 'core-js/features/symbol';
import 'core-js/features/symbol/iterator';
import 'core-js/features/map';
import 'core-js/features/set';
import 'core-js/features/array/find';
```

This will lead to the error in the caption:

![https://i.imgur.com/KJZGpdk.png](https://i.imgur.com/KJZGpdk.png)

I tried to exclude `./node_modules/core-js` in `babel.config.js` following this comment (https://github.com/zloirock/core-js/issues/514#issuecomment-490392862) but only to no success:

```js
module.exports = {
    ...
    ignore: ['./node_modules/core-js']
};
```

`core-js` is v3.1.4 and `@babel/core` is at v7.4.5.

**Comment by zloirock** [comment] 2019-06-21 07:40
Any ideas about how can I reproduce it?

Could I see your configs?

Theoretically, something like that could be if you load `core-js` not before all of your code.

**Comment by d3x7r0** [comment] 2019-06-24 21:30
I'm actually having the exact same error when instancing a `Map` on Safari 12.1.1 on mac os. (no react native involved and I could trace it down to this line of code that I wrote myself:

```js
class MemoryStore {
  constructor() {
    this._data = new Map()
  }
}
```

My .babelrc:
```json
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["@babel/plugin-transform-react-jsx", { "pragma": "h" }],
    "@babel/plugin-syntax-jsx",
    ["@babel/plugin-transform-runtime", { "corejs": 3 }]
  ],
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
      "corejs": 3
    }]
  ]
}
```

I've been struggling with this for a few hours already. If I can do anything to help debug this just let me know.

**Comment by zloirock** [comment] 2019-06-24 21:36
@d3x7r0 at least, you should use `corejs: 3` only in one place - in `preset-env` **OR** in `runtime`.

**Comment by d3x7r0** [comment] 2019-06-24 21:41
@zloirock well it does look like my problem was precisely that. Thanks 👍 

I wonder if the original poster has a similar issue.

**Comment by gsklee** [comment] 2019-06-25 05:02
@d3x7r0 @zloirock not really; actually we don't have a `corejs` config anywhere.

It is a React Native project:

```
module.exports = {
    presets: [
        'module:metro-react-native-babel-preset',
        '@babel/preset-flow',
    ],
    sourceMaps: true,
    plugins: [
        '@babel/transform-flow-strip-types',
        ['@babel/plugin-proposal-class-properties', { loose: true }],
        [
            '@babel/plugin-proposal-decorators',
            {
                legacy: true,
            },
        ],
        'transform-inline-environment-variables',
    ],
};
```

And `module:metro-react-native-babel-preset` can be found here: https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js

**Comment by zloirock** [comment] 2019-06-25 07:16
@gsklee this issue looks like in one place of your code used something like
```js
Map.prototype.get.call(map)
```
but after polyfilling `map` is not an instance of `Map` since it's replaced by `core-js`.

So the problem definitely no in `core-js`, but in the way how you uses it. The global version of `core-js` should be applied before any other code, methods of collections from the version without global namespace pollution should interact only with instances from this version.

**Comment by gsklee** [comment] 2019-06-25 22:40
After I changed the app's initialization code profusely, everything suddenly started to work. Sorry if it seems like I couldn't offer any useful feedback on this issue, because I don't see any slightest relation between my code changes and the issue described here; `import 'core-js/features/symbol';` has been sitting at L1 throughout, before and after.

I'll close the issue since it's no longer an issue for me though.

**Comment by gsklee** [comment] 2019-06-26 02:47
Unfortunately what I stated above was not true; I messed it up with situations where the RN app is executed using the remote debugger's up-to-date V8 engine. When being run without the debugger hooked and using the JSCore that shipped with RN v0.57, as stated within my original report, this error still exists.

**Comment by gsklee** [comment] 2019-06-26 03:18
https://github.com/facebook/metro/issues/218 might be related, not sure.

**Comment by zloirock** [comment] 2019-07-30 21:23
Since, as I wrote above, seems it's not an issue of `core-js`, it's an issue in the way, how it's used, I close this.

**Closed by zloirock** 2019-07-30 21:23 UTC
Labels: can't reproduce

**Comment by arpanoid** [comment] 2020-05-16 22:23
Those who're still having this issue, moving corejs config from `"@babel/plugin-transform-runtime",` to `"@babel/preset-env"` help me fix it.

e.g.
`"@babel/preset-env",
      {
        "corejs": 3
      }`
