### ISSUE TITLE
Map & Set Error in 2.5.3

### ISSUE THREAD

**Issue by xupaopaopaopao** [zloirock/core-js#368] opened 2017-12-15 12:39 UTC
https://github.com/zloirock/core-js/blob/e1c6719a107b92d21125178b859026a04d5d4686/modules/_iter-define.js#L33

With this code, the code below throw error in Android mobile React-Native jscore.
```
[...new Map()];
[...new Set()];
```

**Comment by zloirock** [comment] 2017-12-15 14:22
I'm not completely sure how it can break something. What's the version of Android? Is `spread` operator native or from `Babel`?

**Comment by chrisnojima** [comment] 2017-12-15 15:43
I believe we ran into this as well. Using chrome its fine but on device our android crashes after going from 2.5.1 -> 2.5.3

**Comment by zloirock** [comment] 2017-12-17 09:55
So... Any additional information?

**Comment by chrisnojima** [comment] 2017-12-17 23:24
Debugging this a little bit. Definitely caused by https://github.com/zloirock/core-js/commit/6f9792057de00c873bca6373c1c5eecf66cbc45d. Rolling back to one commit before https://github.com/zloirock/core-js/commit/771b32d5d19e8bf7c292c9f7c9f86deddf755824 and its fine. The stack trace I see is

'TaskQueue: Error with task: Incompatible receiver, Map required!
_validate-collection.js:3:55 
```
 if (!isObject(it) || it._t !== TYPE) throw TypeError('Incompatible receiver, ' + TYPE + ' required!');<<<<
```
_collection-strong.js:120:25
```
    $iterDefine(C, NAME, function (iterated, kind) {
      this._t = validate(iterated, NAME); // target <<<<<<<
      this._k = kind;                     // kind
```

_iter-define.js:26:57
```
    switch (kind) {
      case KEYS: return function keys() { return new Constructor(this, kind); };
      case VALUES: return function values() { return new Constructor(this, kind); };
    } return function entries() { return new Constructor(this, kind); }; <<<<<<<
```

And the react-native code
https://github.com/facebook/react-native/blob/master/Libraries/Lists/ViewabilityHelper.js#L249
```
    const changed = [];
    for (const [key, viewable] of nextItems) { <<<<<<
      if (!prevItems.has(key)) {

```

**Comment by SinLucifer** [comment] 2017-12-25 07:18
There is a js file named BackHandler.Android.js in React-Native, which is used to manage Android BackPress Events. 

``` js
var _backPressSubscriptions = new Set();
RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function() {
  var backPressSubscriptions = new Set(_backPressSubscriptions);
  var invokeDefault = true;
  var subscriptions = [...backPressSubscriptions].reverse();
  for (var i = 0; i < subscriptions.length; ++i) {
    if (subscriptions[i]()) {
      invokeDefault = false;
      break;
    }
  }
```

Because of this code  ` var subscriptions = [...backPressSubscriptions].reverse();` and `Map&Set Error`, when we press BackPress in Android, it will lead these execption:

![image](https://user-images.githubusercontent.com/15983096/34335033-a144a2fa-e986-11e7-8b0d-4a320fb6e299.png)

Reverting back to `v2.5.2` fixed this problem.

**Comment by nevir** [comment] 2017-12-26 20:52
Also see this when running `Array.from(new Set([1, 2, 3]))` on RN-android

**Comment by ttaranov** [comment] 2018-01-03 17:54
run into a related issue I think - although in IE11 and in dev mode with babel, for loops like like 
        for (const [k, v] of myMap) {
        }
produces (sometimes): "Incompatible receiver, Map required!"

downgrading to 2.5.2 fixes IE errors

**Comment by loganfsmyth** [comment] 2018-01-03 18:00
If you're seeing this, please take a minute to put together a reproducible example repository that contains code that reproduces the error, it would help a ton in narrowing this down.

**Comment by nevir** [comment] 2018-01-03 20:45
`Array.from(new Set([1, 2, 3]))` reproduces it

**Comment by zloirock** [comment] 2018-01-03 21:28
IE11:
![image](https://user-images.githubusercontent.com/2213682/34540345-cb3e0902-f106-11e7-8c10-e7ac799aa920.png)
Android 4.4-6:
![image](https://user-images.githubusercontent.com/2213682/34540390-efae9770-f106-11e7-8ce9-de1ec1e1233c.png)
![image](https://user-images.githubusercontent.com/2213682/34540403-0105c502-f107-11e7-9d71-e924f471ae2d.png)
![image](https://user-images.githubusercontent.com/2213682/34540451-3166e028-f107-11e7-9836-3e843aa4b7f6.png)
![image](https://user-images.githubusercontent.com/2213682/34540463-3b7dca0e-f107-11e7-99fb-13dd0948b592.png)
So what about a reproducible example and clarification your environment?

**Comment by lwansbrough** [comment] 2018-01-22 05:45
@zloirock This seems to be reproducible with an app that uses jscore (such as React Native) and a babel-shimmer `for..of` block iterating on a Set/Map.

**Comment by davidpricedev** [comment] 2018-02-01 20:23
I put together a few details of another instance of this problem: https://github.com/twilio/TwilioChatJsReactNative/issues/9

If it helps at all, when I turn on react native's remote debugging, the error goes away. I'm also using android 7.1.1. 

I was able to "fix" it in react native by doing this: 

```bash
yarn add core-js@2.5.2
cp -R node_modules/core-js/* node_modules/fbjs-scripts/node_modules/core-js/
cp -R node_modules/core-js/* node_modules/babel-register/node_modules/core-js/
cp -R node_modules/core-js/* node_modules/babel-runtime/node_modules/core-js/
cp -R node_modules/core-js/* node_modules/metro-bundler/node_modules/core-js/
```

**Comment by philipyun** [comment] 2018-02-06 01:32
i can reproduce this as well.  This occurs on Android API 25, Using Android OS 7.1.1

My RN environment is below.

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 9.2.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

This is an issue with any RN component that uses virtualized list. They use Maps in the implementation if you are using the onViewableItemsChanged prop of the virtualized list. This then brings the error TaskQueue: Map is Required!

do what  @yamafaktory did and downgrading to 2.5.2 worked for me. Clearly an issue is happening with 2.5.3 and React Native specifically

**Comment by nandowalter** [comment] 2018-02-16 07:35
I can confirm that this error occurs also with an Angular 5 project using core-js polyfills.

**Comment by forki** [comment] 2018-03-02 11:14
I can confirm React Native breaks for me with 2.5.3 and works again after downgrad to 2.5.2

**Comment by skovhus** [comment] 2018-03-07 15:53
By looking at [what changes from 2.5.2 to 2.5.3](https://github.com/zloirock/core-js/commit/f96b8d8afaebda5f49ac213627218f841c8692b4) I narrowed it down to this change: https://github.com/zloirock/core-js/issues/236 https://github.com/zloirock/core-js/commit/f96b8d8afaebda5f49ac213627218f841c8692b4#diff-cef85cf90f184a55418f175f3c233f2aR219

FYI @zloirock

**Comment by zloirock** [comment] 2018-03-22 13:37
Ok, I was able to reproduce it... only in FF27. Seems the most cases of this issue was caused conflicts with another not completely correct polyfills. I will revert this change and will publish a patch release soon. This logic will be completely rewritten in `core-js@3`.

**Comment by skovhus** [comment] 2018-03-22 14:13
@zloirock thanks!

**Comment by forki** [comment] 2018-03-22 14:17
Happy to see progress. Thanks

Kenneth Skovhus <notifications@github.com> schrieb am Do., 22. März 2018,
15:14:

**Comment by zloirock** [comment] 2018-03-27 16:21
Fixed in [`2.5.4`](https://github.com/zloirock/core-js/releases/tag/v2.5.4) and [`3.0.0-alpha.1`](https://github.com/zloirock/core-js/releases/tag/v3.0.0-alpha.1).

**Closed by zloirock** 2018-03-27 16:21 UTC
Labels: bug

**Comment by HaykPolymorphic** [comment] 2018-03-29 14:17
hi
I am using 2.5.4 version in my react-native project. But I am facing this error for android. 
![screenshot_20180329-180410](https://user-images.githubusercontent.com/33617909/38093924-6e66f9be-337d-11e8-8f55-cec5dfa25d3a.png)

Can you please advise?

**Comment by kalyanijamunkar10** [comment] 2018-08-21 06:07
![screenshot_2018-08-20-12-34-40-292_com contentstream](https://user-images.githubusercontent.com/27677593/44383438-62405380-a536-11e8-8931-77b2e5aaf4c3.png)
 facing same issue, please provide any information. tried using 2.4.0, 2.5.4 and @3 but not working
