### ISSUE TITLE
String.prototype.split is undefined in Chrome 41

### ISSUE THREAD

**Issue by kevinxh** [zloirock/core-js#375] opened 2018-02-07 23:51 UTC
Sorry for the legacy Chrome version issue (it is used for SEO related stuff).

It looks like `String.prototype.split` is incorrectly overridden to be undefined, which causes every other calls of `string.split()` to throw an error of `Uncaught TypeError: undefined is not a function`

To verify that the issue is related to `core-js`, I deleted everything in `/node_modules/core-js/modules/es6.regexp.split.js`, and the errors went away.

Note: this is **not** happening on the latest Chrome.

**Comment by zloirock** [comment] 2018-02-08 00:03
It's [tested](https://saucelabs.com/beta/tests/aa95c1a36a4e48948b9114acc7020ae3/watch) in Chrome 41. Could you add a reproducible example?

**Comment by zloirock** [comment] 2018-03-06 08:46
Closed as `can't reproduce`.

**Closed by zloirock** 2018-03-06 08:46 UTC
Labels: can't reproduce
