### ISSUE TITLE
TypeError Cannot convert undefined or null to object     at hasOwnProperty (<anonymous>)

### ISSUE THREAD

**Issue by DamienCompere** [zloirock/core-js#867] opened 2020-10-02 09:49 UTC
Hello, 
After a yarn upgrdade I have the following error : 
```
has.js:4 Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at ./node_modules/core-js/internals/has.js.module.exports
```
I tried to exclude `./node_modules/core-js` from my` '@babel/preset-env'` but still have the error, 
Do you know how to fix it ?

**Comment by zloirock** [comment] 2020-10-27 08:32
Please, add a reproducible example. Without it, I can't say anything. Most likely, it's not a `core-js` issue.

**Comment by zloirock** [comment] 2020-11-05 18:29
Closed as `can't reproduce`.

**Closed by zloirock** 2020-11-05 18:29 UTC
Labels: can't reproduce

**Comment by tinhnghiadn3** [comment] 2022-09-21 17:02
> Hello, After a yarn upgrdade I have the following error :
> 
> ```
> has.js:4 Uncaught TypeError: Cannot convert undefined or null to object
>     at hasOwnProperty (<anonymous>)
>     at ./node_modules/core-js/internals/has.js.module.exports
> ```
> 
> I tried to exclude `./node_modules/core-js` from my` '@babel/preset-env'` but still have the error, Do you know how to fix it ?

Have you fixed it? I need your solution, please reply me.
