### ISSUE TITLE
NS_ERROR_XPC_BAD_OP_ON_WN_PROTO on old Firefox

### ISSUE THREAD

**Issue by nickbar86** [zloirock/core-js#374] opened 2018-02-07 15:18 UTC
Same as #254 
firefox version 20

**Comment by zloirock** [comment] 2018-02-07 16:42
Seems it's a `zone.js` issue - it also wraps many js native methods. Closed as a duplicate of #254. If you have a reproducible example without `zone.js`, please, add it to #254 and I'll try to fix it.

**Closed by zloirock** 2018-02-07 16:42 UTC
