### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by leethree** [zloirock/core-js#1237] opened 2023-04-12 11:25 UTC
In React Native, we use 'core-js/stable/url' to polyfill the URL object. but since ~3.25 we are having this issue with cyclical dependency:

![simulator_screenshot_7E7DD935-0868-4AE1-BB72-DACF87C74635](https://user-images.githubusercontent.com/648142/231441358-5375cebb-fa6b-4380-af1a-f9250095226d.png)

It looks like the following to modules are calling each other:

`core-js/internals/make-built-in.js`:

```js
Function.prototype.toString = makeBuiltIn(function toString() {
  return isCallable(this) && getInternalState(this).source || inspectSource(this);
}, 'toString');
```

It's using `inspectSource`. 

`core-js/internals/inspect-source.js`:

```js
var functionToString = uncurryThis(Function.toString);

// this helper broken in `core-js@3.4.1-3.4.4`, so we can't use `shared` helper
if (!isCallable(store.inspectSource)) {
  store.inspectSource = function (it) {
    return functionToString(it);
  };
}
```

And it's using `Function.toString` which is overridden by `make-built-in.js`, which causes the infinite call loop.

This issue is probably caused by import order. The temporary workaround is to import `/inspect-source.js` before importing the polyfill. But we still believe it would be great to figure out how to resolve this properly.

**Comment by zloirock** [comment] 2023-04-12 21:43
Could you add a reproducible example? It looks like incorrect `core-js` usage / transpiler settings.

**Comment by zloirock** [comment] 2023-04-24 11:19
Closed as `can reproduce`. Please, provide a reproducible example and I'll try to help you.

**Closed by zloirock** 2023-04-24 11:19 UTC
Labels: can't reproduce

**Comment by Reeywhaar** [comment] 2023-07-06 00:12
Indeed patched `toString` [calls](https://github.com/zloirock/core-js/blob/80b2e800fd725e78870d06d1a9fbfa8b1e10d343/packages/core-js/internals/make-built-in.js#L53) `inspectSource` and `inspectSource` [calls](https://github.com/zloirock/core-js/blob/80b2e800fd725e78870d06d1a9fbfa8b1e10d343/packages/core-js/internals/inspect-source.js#L5) `toString`

**Comment by zloirock** [comment] 2023-07-06 00:54
@Reeywhaar `inspectSource` calls *cached* `toString`.

**Comment by Reeywhaar** [comment] 2023-07-06 09:28
@zloirock thank you for enlightenment!

So, I've fixed my problem by adding the `inlineRequires: false` to `my metro.config.js`. This [comment helped](https://github.com/facebook/hermes/issues/135#issuecomment-808817771).

```js
const config = {
  transformer: {
    getTransformOptions: async () => {
      return {
        transform: {
          inlineRequires: false,
        },
      }
    },
  },
}
```

It has nothing to do with `core-js`.

**Comment by Titozzz** [comment] 2023-09-22 09:07
if you don't want to set all to false, you can do this
```
 getTransformOptions: () => ({
        transform: {
          experimentalImportSupport: true,
          inlineRequires: true,
          // Fix for core-js cyclic dependency that lead to require stack exceeded error
          nonInlinedRequires: ['../internals/inspect-source'],
        },
      }),
```
