### ISSUE TITLE
IE11: DataView operation access beyond specified buffer length

### ISSUE THREAD

**Issue by MartinJohns** [zloirock/core-js#394] opened 2018-04-19 14:38 UTC
When running an Angular app that uses core-js v2.5.5 I get this error right on the start:

```
DataView operation access beyond specified buffer length
```

The error refers to this code:

```javascript
  // iOS Safari 7.x bug
  var view = new $DataView(new $ArrayBuffer(2));
  var $setInt8 = $DataView[PROTOTYPE].setInt8;
  view.setInt8(0, 2147483648);  // <--- This line here
  view.setInt8(1, 2147483649);
```

Is there any reason why you assign `2147483648` to an 8bit array?

**Comment by zloirock** [comment] 2018-04-20 16:52
It's added, as you can see in the comment, for testing and fixing incorrect conversions in those methods in iOS Safari 7. It's tested in IE11 and downloaded from `npm` hundreds of thousands of times without any related issues. I have no any ideas about it, so, please, add a reproducible example.

**Comment by zloirock** [comment] 2018-04-27 10:30
Closed as `can't reproduce`.

**Closed by zloirock** 2018-04-27 10:30 UTC
Labels: can't reproduce
