### ISSUE TITLE
document undefined?

### ISSUE THREAD

**Issue by gordanyang** [zloirock/core-js#426] opened 2018-08-28 11:13 UTC
in packages/core-js/internals/microtask.js
``` var node = document.createTextNode(''); ``` should be ``` var node = global.document.createTextNode(''); ```  ??

```
else if (Observer && !(global.navigator && global.navigator.standalone)) {
    var toggle = true;
    var node = document.createTextNode('');
    new Observer(flush).observe(node, { characterData: true }); // eslint-disable-line no-new
    notify = function () {
      node.data = toggle = !toggle;
    };
  // environments with maybe non-completely correct, but existent Promise
  } 
```

**Comment by zloirock** [comment] 2018-08-28 13:07
`document` is a global variable - here is no difference between `global.document`. Does it cause an error for you?

**Comment by gordanyang** [comment] 2018-08-28 13:28
yes,in my case.
![image](https://user-images.githubusercontent.com/4629246/44725967-3e1ddd00-ab09-11e8-9837-42509ddc92b0.png)
![image](https://user-images.githubusercontent.com/4629246/44726021-568df780-ab09-11e8-97bd-65eb1075d66f.png)

**Comment by zloirock** [comment] 2018-09-12 08:33
Something strange. Could you add any info about your environment?

**Comment by zloirock** [comment] 2018-10-19 06:41
Closed as `can't reproduce`.

**Closed by zloirock** 2018-10-19 06:41 UTC
Labels: can't reproduce
