### ISSUE TITLE
toString ie11 SCRIPT5002

### ISSUE THREAD

**Issue by thejahweh** [zloirock/core-js#543] opened 2019-05-09 14:01 UTC
I currently wanted to switch from webpack ts-loader to babel-loader. And experienced an issue with a core-js@3 polyfill for toString:
```js
// add fake Function#toString for correct work wrapped methods / constructors with methods like LoDash isNative
})(Function.prototype, 'toString', function toString() {
  return typeof this == 'function' && getInternalState(this).source || nativeFunctionToString.call(this);
});
```
IE11 gives me the error:
```error
SCRIPT5002: Function.prototype.toString: 'this' ist kein Function-Objekt
```

**Comment by zloirock** [comment] 2019-05-10 11:15
You can see this issue if you run `Function.prototype.toString` on non-functions. `core-js` just add a wrapper for `Function.prototype.toString`, so you can see it in a stack trace.

If you still think that the problem in `core-js`, please, add a reproducible example.

**Comment by thejahweh** [comment] 2019-05-15 06:56
If you want you can close it. Because I don't really understand whats going on here and why this is happening, therefore I can't help to reproduce it.

What I've done to get it to work is simply add the `ts-loader` before the `babel-loader` so it gets transpiled first from TypeScript.

**Comment by zloirock** [comment] 2019-05-19 10:51
Closed as `can't reproduce`.

**Closed by zloirock** 2019-05-19 10:51 UTC
Labels: can't reproduce
