### ISSUE TITLE
'toISOString is not a function' when using 'redux-devtools-extension'

### ISSUE THREAD

**Issue by kuncevic** [zloirock/core-js#347] opened 2017-10-24 02:16 UTC
Here is the thread https://github.com/ngrx/platform/issues/61 with detailed issue.

Basically there is something is going on when using https://github.com/gaearon/redux-devtools chrome extension, the issue is taking place only when extension is enabled.

I debug the issue for some time and discovered that it is related to `import 'core-js/es6/date';`  polyfil.

Seems like that is the piece of code which is causing an error:
```
$export($export.P + $export.F * __webpack_require__("../../../../core-js/modules/_fails.js")(function(){
  return new Date(NaN).toJSON() !== null || Date.prototype.toJSON.call({toISOString: function(){ return 1; }}) !== 1;
}), 'Date', {
  toJSON: function toJSON(key){
    var O  = toObject(this)
      , pv = toPrimitive(O);
    return typeof pv == 'number' && !isFinite(pv) ? null : O.toISOString();
  }
});

```
So if I comment the `import 'core-js/es6/date';` in my `polyfils.ts` - all good, then I can use `redux-devtools`

Not sure if this one is related https://github.com/zloirock/core-js/issues/326

**Comment by zloirock** [comment] 2017-10-24 11:36
It's completely correct [step by step](https://tc39.github.io/ecma262/#sec-date.prototype.tojson) implementation of `Date.prototype.toJSON` and it's not polyfilled in modern engines. Could you add more info about your environment and provide a simple reproducible example?

**Comment by kuncevic** [comment] 2017-10-26 04:14
>Could you add more info about your environment and provide a simple reproducible example? 
@zloirock I will come back on that

**Comment by richinator38** [comment] 2017-11-10 15:47
Using Angular 4.3 I could get this by lazy loading modules...it didn't occur before that change.

**Comment by casc99** [comment] 2017-11-13 14:33
as in [https://github.com/zalmoxisus/redux-devtools-extension/issues/315](https://github.com/zalmoxisus/redux-devtools-extension/issues/315) this got solved moving StoreDevtoolsModule.instrument at the top of the imports in the app module:
```
@NgModule({

  imports: [
    StoreDevtoolsModule.instrument({
      maxAge: 15
    }),
    BrowserModule,
    BrowserAnimationsModule,
    // ..
```

**Comment by zloirock** [comment] 2017-11-16 16:00
Closed as `can't reproduce`.

**Closed by zloirock** 2017-11-16 16:00 UTC
Labels: can't reproduce
