### ISSUE TITLE
Object doesn't support property or method 'Symbol(Symbol.iterator)'

### ISSUE THREAD

**Issue by SDVII** [zloirock/core-js#693] opened 2019-11-11 13:04 UTC
* core-js is imported, yet this error is being thrown:
`SCRIPT438: Object doesn't support property or method 'Symbol(Symbol.iterator)_a.89m09f8xjln'` in eval code
* `Symbol` is recognizable in IE's console.

**Comment by zloirock** [comment] 2019-11-11 13:22
That means that you try to iterate something non-iterable -) I'm not sure that it's a `core-js` issue. If you think so - please, specify what iterator you expect.

**Comment by SDVII** [comment] 2019-11-11 13:44
I am not using any iterators personally, the error is being thrown after transpiling a library

**Comment by zloirock** [comment] 2019-11-11 13:46
So try to find the place which causes this issue in your code or create a reproducible example.

**Comment by SDVII** [comment] 2019-11-11 13:47
I'll see if I can create a reproducible example. Thanks for the quick response.

**Comment by zloirock** [comment] 2019-11-17 06:12
Closed as `can't reproduce`. Feel free to provide a reproducible example.

**Closed by zloirock** 2019-11-17 06:12 UTC
Labels: can't reproduce
