### ISSUE TITLE
''.startsWith('') should return true

### ISSUE THREAD

**Issue by sledorze** [zloirock/core-js#321] opened 2017-07-28 14:20 UTC
''.startsWith('') returns false (core-js 2.4.1) whereas on chrome it returns true.

Based on this documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

```
if (!String.prototype.startsWith) {
    String.prototype.startsWith = function(searchString, position){
      return this.substr(position || 0, searchString.length) === searchString;
  };
}
```

it should returns true

**Comment by zloirock** [comment] 2017-07-30 11:00
I checked it, it returns `true`. Could you add a reproducible example and more info about the environment?

**Comment by zloirock** [comment] 2017-08-06 15:46
Closed as `can't reproduce`.

**Closed by zloirock** 2017-08-06 15:46 UTC
Labels: can't reproduce
