### ISSUE TITLE
IE11 Object does not support the 'endswith' property or method

### ISSUE THREAD

**Issue by siylau** [zloirock/core-js#1068] opened 2022-04-11 10:25 UTC
"core-js": "^3.21.1",
"webpack": "^5.65.0",
node:v14.18.2

**Comment by siylau** [comment] 2022-04-12 06:51
> Sorry, I don't understand what do you mean.

like IE11,use import'core-js/features/string/ends-with', However, String.prototype.endswith() was not handled.

**Comment by siylau** [comment] 2022-04-12 07:46
> Maybe because it should be `.endsWith`?

<img width="489" alt="image" src="https://user-images.githubusercontent.com/37366525/162907993-18abaadb-9c41-43a5-9f40-62614602bf79.png">

![image](https://user-images.githubusercontent.com/37366525/162907861-fab703ed-0bc4-4f44-b37f-7808e40b0721.png)
What should I do.

**Comment by siylau** [comment] 2022-04-12 08:01
> Maybe because it should be `.endsWith`?
![image](https://user-images.githubusercontent.com/37366525/162911255-3514e019-1bf6-4f03-a7b3-2c12ed214d72.png)

Do you need any other information? I hope you can help me deal with this problem.

**Comment by zloirock** [comment] 2022-04-12 09:24
![image](https://user-images.githubusercontent.com/2213682/162927193-900cd56c-95c4-4ec9-b240-2f065d012db6.png)

Sorry, I can't reproduce it. Please, make sure that you load it and add a reproducible example.

**Comment by zloirock** [comment] 2022-04-14 23:46
Closed as `can't reproduce`.

**Closed by zloirock** 2022-04-14 23:46 UTC
Labels: can't reproduce
