### ISSUE TITLE
Uncaught TypeError when using core-js-pure with babel-runtime

### ISSUE THREAD

**Issue by deemoding** [zloirock/core-js#705] opened 2019-11-26 16:38 UTC
step to reproduction:

```bash
git clone https://github.com/deemoding/React-boilerplate
cd React-boilerplate
git checkout core-js-pure
npm i
npm start
```

open `http://localhost:65534`

what happens:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at module.exports (has.js:4)
    at Object.module.exports [as f] (well-known-symbol.js:14)
    at module.exports (define-well-known-symbol.js:9)
    at eval (es.symbol.iterator.js:5)
    at Object../node_modules/core-js-pure/modules/es.symbol.iterator.js (main.bundle.js:6415)
    at __webpack_require__ (main.bundle.js:727)
    at fn (main.bundle.js:101)
    at eval (iterator.js:1)
    at Object../node_modules/core-js-pure/es/symbol/iterator.js (main.bundle.js:3797)
```

**Comment by zloirock** [comment] 2019-11-26 18:41
It looks like #689, but your example can be reproduced even in modern engines. Now I haven't time to debug it, so I'll play with it a little later.

**Comment by zloirock** [comment] 2020-01-10 16:01
A will not have a chance to explore it shortly, so marked as `help wanted`.

**Comment by DamienCompere** [comment] 2020-10-02 09:55
I have the same issue, did you fix it ?

**Comment by deemoding** [comment] 2020-10-23 06:27
> I have the same issue, did you fix it ?

I update to webpack5, and update all my dependencies to latest. Then It works. You can refer to [this](https://github.com/deemoding/React-boilerplate/tree/webpack5)

By the way, you can use babel-runtime. I have tested and it works.

**Closed** 2021-04-07 16:32 UTC
Labels: help wanted
