### ISSUE TITLE
Incorrect type for Set in IE

### ISSUE THREAD

**Issue by arshtepe** [zloirock/core-js#380] opened 2018-02-16 09:39 UTC
```
export function getObjectType(obj) {
    return ({}).toString.call(obj)
};
```
getObjectType(new Set())
In normal browser result  [object Set] , but in IE 11 [object Object]

**Comment by zloirock** [comment] 2018-02-16 09:50
You will have `[object Set]` only with correct / polyfilled `Object#toString` with `Symbol.toStringTag` support. It's impossible in the version without global namespace pollution. In the global version, if you load only some parts of `core-js`, should be loaded `Object#toString` polyfill, not just `Set`.

**Comment by arshtepe** [comment] 2018-02-16 09:53
@zloirock I use core-js by babel-runtime@6.23.0 . I need serialize Set to object like 
```js
{
 type: getObjectType(obj),
 value: [...set]
}
```
and for deserialize for Set i need type.

**Comment by zloirock** [comment] 2018-02-16 09:57
As I wrote, it's impossible in this case. If you need `@@toStringTag` support in `Object#toString`, you should use the global version. Duplicate of #199.

**Closed by zloirock** 2018-02-16 09:57 UTC

**Comment by zloirock** [comment] 2018-02-16 09:58
As an option, you can try `return Object(obj)[SymbolToStringTag] || ({}).toString.call(obj)`.

**Comment by arshtepe** [comment] 2018-02-16 10:02
@zloirock I have checked. I have include $.set-to-string-tag

**Comment by zloirock** [comment] 2018-02-16 10:08
One more time: for adding support `@@toStringTag` to `Object#toString`, we should manky-patch `Object#toString`. It's impossible without global namespace pollution. `$.set-to-string-tag` (btw, which version of `core-js` you use? This filename convention was changed IIRC 2 years ago) adds `@@toStringTag` to collections prototype, so you can use a fallback as I proposed above, but does not patch `Object#toString`.

**Comment by arshtepe** [comment] 2018-02-16 10:08
@zloirock  I have 2 files, first it is polyfill for IE and looks like
```js
require("core-js/es7/string");
require("core-js/es6/array");
require("core-js/es6/string");
require("core-js/es7/array");
require("core-js/modules/es6.object.assign");
require("core-js/modules/$.set-to-string-tag");
window.Promise = require("core-js/library/fn/promise");// for webpack
```
second it is application which build by webpack + babel. Is it may be reason why it doesn't work ?

**Comment by zloirock** [comment] 2018-02-16 10:10
Because missed `core-js/fn/object/to-string` or `core-js/es6/object`.

**Comment by arshtepe** [comment] 2018-02-16 10:16
@zloirock in application file, I have
`__webpack_require__(/*! ../modules/es6.object.to-string */ "./node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.to-string.js")`

**Comment by zloirock** [comment] 2018-02-16 10:20
`core-js/library/modules/es6.object.to-string` is an empty cap for non-global version. Should be `core-js/modules/es6.object.to-string`.

**Comment by zloirock** [comment] 2018-02-16 10:23
BTW, please, never use `core-js(/library)/modules/*` if you don't completely understand how it works.

**Comment by arshtepe** [comment] 2018-02-16 10:28
@zloirock  Thank you. It works.
