### ISSUE TITLE
The minor version of corejs 3.27.1 is automatically upgraded to 3.27.2, causing node memory leaks

### ISSUE THREAD

**Issue by 10086XIAOZHANG** [zloirock/core-js#1175] opened 2023-02-06 06:19 UTC

**Comment by zloirock** [comment] 2023-02-06 06:22
What? -)

**Comment by 10086XIAOZHANG** [comment] 2023-02-06 06:25
![image](https://user-images.githubusercontent.com/19355833/216898127-2bf0ca08-853b-433c-98c9-815d52f533f4.png)
1.30 node ssr release version, the core-js version is automatically upgraded from 3.27.1 to 3.27.2, causing the memory to rise all the time, after locking the version to 3.27.1, the memory stabilizes. It is suspected that this code modification caused it

**Comment by zloirock** [comment] 2023-02-06 06:36
I don't see here possible memory leaks, https://github.com/zloirock/core-js/blob/v3.27.2/packages/core-js/internals/queue.js, it's just the unification of logic and it was already used, for example, in `Promise` polyfill.

**Comment by zloirock** [comment] 2023-02-06 07:12
Please, create a reproducible example specifying the environment where it happens.

**Comment by zloirock** [comment] 2023-02-08 05:40
@10086XIAOZHANG ?

**Comment by zloirock** [comment] 2023-02-13 17:44
Closed as `can't reproduce`.

**Closed by zloirock** 2023-02-13 17:44 UTC
Labels: can't reproduce
