### ISSUE TITLE
ie11 bug

### ISSUE THREAD

**Issue by guofeng11** [zloirock/core-js#408] opened 2018-06-08 10:06 UTC
I code like 
<div id="output"></div>
<script src="https://unpkg.com/core-js-bundle@3.0.0-beta.3/minified.js"></script>

<script>
    const getMessage = () => "Hello World";
    document.getElementById('output').innerHTML = getMessage();
</script>

// Chrome 38 Symbol has incorrect toString conversion
module.exports = !__webpack_require__(5)(function () {
  // eslint-disable-next-line no-undef
  String(Symbol());
});
![qq 20180608180509](https://user-images.githubusercontent.com/19421502/41152559-8cc34452-6b46-11e8-8150-170a9b6b1a39.jpg)

**Comment by zloirock** [comment] 2018-06-08 11:02
I have no ideas. [It's tested in IE11.](https://saucelabs.com/beta/tests/b7fc9c2281a74c6abf254882c2ac7bf3/watch). `webpack_require(5)` is [this method](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/fails.js) which contains `try / catch`.

**Comment by zloirock** [comment] 2018-06-30 03:34
Closed as `can't reproduce`.

**Closed by zloirock** 2018-06-30 03:34 UTC
Labels: can't reproduce
