### ISSUE TITLE
Is that `Array.prototype.concat` will be removed during importing polyfilll?

### ISSUE THREAD

**Issue by aleen42** [zloirock/core-js#1034] opened 2022-01-05 08:34 UTC
Recently, I have found that if I have shimmed `Function.prototype.bind` at first:

```js
var $A = Array.from = function (iterable) {
    if (!iterable) return [];
    if (iterable.toArray) {
        return iterable.toArray();
    } else {
        var results = [];
        for (var i = 0; i < iterable.length; i++)
            results.push(iterable[i]);
        return results;
    }
};

Function.prototype.bind = function () {
    var __method = this, args = $A(arguments), object = args.shift();
    return function () {
        return __method.apply(object, args.concat($A(arguments)));
    };
};
```

And then, when running in the process of importing `core-js/shim`, `Array.prototype.concat` has been removed, and an exception was thrown when `core-js` tries to call shimmed `Function.prototype.bind`.

I just want to confirm whether it is due to the commit (277cb333980e6c3f5fd37f8ed9867de272d027e9), which wants to protect some built-in methods?

**Comment by zloirock** [comment] 2022-01-05 09:44
> Is that `Array.prototype.concat` will be removed during importing polyfill?

Only in case if it should be polyfilled and immediately will be replaced to the proper method.

> And then, when running in the process of importing `core-js/shim`, `Array.prototype.concat` has been removed, and an exception was thrown when `core-js` tries to call shimmed `Function.prototype.bind`.

I can't reproduce that. I see only some possible issues from your incomplete `.bind` implementation that does not work with constructors.

**Comment by zloirock** [comment] 2022-01-05 09:50
For example, your code, `core-js` import and `core-js` test case:

![image](https://user-images.githubusercontent.com/2213682/148197181-46b90381-fcfa-4334-a1b6-6b4a16a7a860.png)

Issues only in your `.bind`.

**Comment by aleen42** [comment] 2022-01-05 10:27
In my case, I have caught an error thrown when accessing `args.concat` in my code. It seems wiered.

**Comment by zloirock** [comment] 2022-01-05 10:41
Please, add a reproducible example. I can't reproduce it just with this code.

**Comment by aleen42** [comment] 2022-01-06 06:32
@zloirock Denis, we can reproduce via my commit (https://github.com/aleen42/core-js/commit/937d46474547280a43f08b380ebc4adfb116dee8)

```
$ npm run test-pollution

> test-pollution
> karma start -f=pollution.js,packages/core-js-bundle/index.js,tests/bundles/tests.js

PhantomJS 2.1.1 (Mac OS 0.0.0) WARN: 'Possible Unhandled Promise Rejection:', TypeError: undefined is not a constructor (evaluating 'args.concat($A(arguments))')
http://localhost:9876/base/pollution.js?8927b7e12418c94e8f945840857d4b03b1afa951:16:46
Error@http://localhost:9876/base/packages/core-js-bundle/index.js?3fbec792f23e50e2ca19b5626f36c32439075414:2854:48
done@http://localhost:9876/base/node_modules/qunit/qunit/qunit.js?c9a269d8ad4db3a08f5a483c41b9bce84062fc4f:2082:26
advanceTestQueue@http://localhost:9876/base/node_modules/qunit/qunit/qunit.js?c9a269d8ad4db3a08f5a483c41b9bce84062fc4f:1985:11
advance@http://localhost:9876/base/node_modules/qunit/qunit/qunit.js?c9a269d8ad4db3a08f5a483c41b9bce84062fc4f:1940:23
unblockAndAdvanceQueue@http://localhost:9876/base/node_modules/qunit/qunit/qunit.js?c9a269d8ad4db3a08f5a483c41b9bce84062fc4f:4321:28
http://localhost:9876/base/node_modules/qunit/qunit/qunit.js?c9a269d8ad4db3a08f5a483c41b9bce84062fc4f:1634:19
PhantomJS 2.1.1 (Mac OS 0.0.0) ERROR
```

**Comment by aleen42** [comment] 2022-01-06 06:52
I think `core-js` can try to remove all external shims at the start point to avoid such a problem, but it seems not necessary. It is just a suggestion. The main issue is can we avoid removing `Array.prototype.concat`?

**Comment by zloirock** [comment] 2022-01-06 07:02
@aleen42 it's not an external shim, since it's an incomplete polyfill that unconditionally replaces the proper feature, it's a case of a broken environment. Need to check, most likely this error happens between `Array.prototype.concat` removing and adding the proper polyfill. However, I'm not sure that it's something that should be fixed since it's a case of a broken environment.

**Comment by aleen42** [comment] 2022-01-06 07:09
A possible direction is to confirm using native methods or shim methods of `core-js` rather than untrusted ones, during the procedure of removing `Array.prototype.concat` and replacing back.

**Comment by zloirock** [comment] 2022-01-06 07:13
Yes, I think I'll do something like that since such `.bind` was popular some time ago.

**Comment by aleen42** [comment] 2022-01-06 07:20
👍🏼

**Closed** 2022-01-06 07:54 UTC
Labels: broken environment

**Comment by zloirock** [comment] 2022-01-06 07:55
Added a workaround.

Note: Most likely, this check will be removed in `core-js@4` with ES3 support.

Thanks for the issue.

**Comment by aleen42** [comment] 2022-01-06 08:04
@zloirock It is better to add a testing case for such a polluted environment.

**Comment by zloirock** [comment] 2022-01-06 08:11
Anyway, we can't detect all possible cases of broken in the userland environment. Now, we have fallbacks for cases with missed `.bind`, in case of removing ES3 support they implied to be removed. Leaving such code will significantly increase the size of minimalistic bundles and it will significantly reduce pluses of removing ES3 support.

**Comment by aleen42** [comment] 2022-01-06 08:17
OK, it is just a choice, and feel free to close it. #1035

**Comment by zloirock** [comment] 2022-01-06 08:33
My previous comment was a continuation of the comment what was before.

> @zloirock is it better to add a testing case for such a polluted environment? But it seems not proper to add polluted code into this repository.
> #1035

I'm not sure that makes sense - it's a too specific case, I'll think about it, thanks.
