### ISSUE TITLE
Latest is causing memory heap issues in jest

### ISSUE THREAD

**Issue by DavidLozzi** [zloirock/core-js#955] opened 2021-07-01 20:43 UTC
We had `core-js` in our setup files in our jest tests for a React 16 app. 

We had `"core-js": "^3.6.5",` in our package.json file, and 2 days ago, our jests started failing with:

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

In debugging and getting the heap memory, we saw many many recurisve loops of `nativeSort`

![image](https://user-images.githubusercontent.com/3543383/124186840-e3f8af80-da8a-11eb-8601-592e370bce1a.png)

I searched all of our code and node_modules and found this library having a function w/ that name. So I removed the reference from our tests and everything runs fine!

I'm not sure why we even had this in here, as our tests run fine without it. We also have changed our package removing the `^` so that it stays at v3.6.5. It appears 3.15.0 is causing this issue.

**Comment by zloirock** [comment] 2021-07-01 21:05
Funny. It could happen on stable sort feature detection. What engine? Could you add a reproducible example?

**Comment by zloirock** [comment] 2021-07-01 21:09
...nope, `nativeSort` used only in the case of native stable sort support in wrappers for fixing arguments.

**Comment by zloirock** [comment] 2021-07-05 09:39
Still waiting for a reproducible example and details.

**Comment by zloirock** [comment] 2021-07-08 16:34
Closed as `can't reproduce`. If you wanna get help - please, write details.

**Closed by zloirock** 2021-07-08 16:34 UTC
Labels: can't reproduce
