### ISSUE TITLE
TypeError: Cannot convert undefined to object

### ISSUE THREAD

**Issue by noesting** [zloirock/core-js#353] opened 2017-11-08 14:17 UTC
Hello,

I'm developing a WebApp using Ionic 3 and Meteor. When I connect to my page i get the following error: 

TypeError: Cannot convert undefined to object

![grafik](https://user-images.githubusercontent.com/4244926/32553028-027eae5a-c496-11e7-83cd-54bd31cd6196.png)

I use the npm Package meteor-client-bundler (https://github.com/Urigo/meteor-client-bundler). Searching for a solution led me here https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124 and here https://github.com/Urigo/meteor-client-bundler/issues/41#issuecomment-323585625

So I think this might be an issue in core-js.

Thanks in advance for your help.

Some information about my system:

Meteor Version:
```
meteor --version
Meteor 1.6
```

Ionic Info:
```
ionic info

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.2 browser 4.1.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 3.10.10 
    OS                : Linux 4.4
```

npm -g list --depth=0:
```
npm -g list --depth=0
/usr/lib
├── cordova@6.5.0
├── ionic@3.17.0
├── meteor-client-bundler@0.3.0
├── node-pre-gyp@0.6.34
├── npm@3.10.10
├── npm-check-updates@2.13.0
└── shipit-cli@3.0.0
```

**Comment by zloirock** [comment] 2017-11-09 17:01
That looks like a bug (#300) which was fixed in `core-js@2.5.0`, however, I'm not sure without a reproducible example.

**Comment by noesting** [comment] 2017-11-10 09:42
My core-js version is 2.5.1

The problem were old browser versions. I got the issue in the following Browsers
- Firefox 52.0.2 (64-Bit)
- Chromium Version 53.0.2785.143
- Opera 12.16
- Edge 38.x

After updating my browsers it seems to work except for IE 11.

**Comment by zloirock** [comment] 2017-11-16 15:46
As I wrote, I can't say anything without a reproducible example. So I close it as `can't reproduce`.

**Closed by zloirock** 2017-11-16 15:46 UTC
Labels: can't reproduce
