### ISSUE TITLE
Uncaught TypeError: Cannot delete property 'from' of function Uint8Array error in Android 6.0 and core-js 3.x

### ISSUE THREAD

**Issue by zaaack** [zloirock/core-js#564] opened 2019-05-25 10:06 UTC
Uncaught TypeError: Cannot delete property 'from' of function Uint8Array 

this error comes from eithor exportStatic  or exportProto
https://github.com/zloirock/core-js/blob/e3b99db7668d26ad10bb3dce069a4f85673f2390/packages/core-js/internals/array-buffer-view-core.js#L73

But it's normal in 2.6.5/

**Comment by zloirock** [comment] 2019-05-25 10:58
Sorry, I can't reproduce it. It's tested in Android 6.0:

![image](https://user-images.githubusercontent.com/2213682/58368389-a40f8780-7f16-11e9-8848-8679334cb5c8.png)

Could you add a reproducible example?

**Comment by zaaack** [comment] 2019-05-25 11:08
@zloirock Sorry, the error comes from user's report, and we didn't have an Android 6.0 device to reproduce, only an error message without error stack. I'll try find the reproducible code after install an android VM.

**Comment by zloirock** [comment] 2019-06-02 01:52
Closed as `can't reproduce`. Waiting for a reproducible example to revisiting it.

**Closed by zloirock** 2019-06-02 01:52 UTC
Labels: can't reproduce

**Comment by treeandgrass** [comment] 2020-09-29 11:13
i get same problem
array-buffer-view-core.js?ebb5:90 Uncaught TypeError: Cannot delete property 'from' of function Int8Array() { [native code] }

**Comment by simonbrent** [comment] 2021-04-28 13:04
I get the same, specifically from the line 

`delete TypedArrayConstructor[KEY];`

This happens in the wild for certain pages of the website I work in, for users with Chrome 45. I have reproduced it using an old version of Chromium, downloaded from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/338387/

**Comment by zloirock** [comment] 2021-04-28 13:31
@simonbrent I haven't a Windows machine at hand, so I can't check it. But I know that this kind of bug is possible in some buggy engine versions. I'll add `try / catch` here, most likely it will help.

**Comment by simonbrent** [comment] 2021-04-28 13:34
@zloirock Thanks. I have tracked it further to any part of our site which uses d3, so I guess my next task will be to ask its maintainers to update, once you have released a fix :-)

**Comment by simonbrent** [comment] 2021-04-28 14:33
I can confirm that this fix solves the problem I was seeing. Thanks a lot!
