### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by frontendphil** [zloirock/core-js#648] opened 2019-09-18 14:34 UTC
I hope this isn't a duplicate. Lately, we're seeing errors popping up in our monitoring system with this error message `Object prototype may only be an Object or null: undefined`. 

The stack trace points to:

```es6
if (!NATIVE_ARRAY_BUFFER_VIEWS || !TypedArrayPrototype || TypedArrayPrototype === ObjectPrototype) {
   TypedArrayPrototype = TypedArray.prototype;
   if (NATIVE_ARRAY_BUFFER_VIEWS)
     for (NAME in TypedArrayConstructorsList) {
       //                | setPrototypeOf fails
       if (global[NAME]) setPrototypeOf(global[NAME].prototype, TypedArrayPrototype);
     }
 }
```

in `array-buffer-view-core`. 

Were seeing this error pop up for the following browsers:

![Screenshot 2019-09-18 at 16 29 26](https://user-images.githubusercontent.com/187786/65157740-815b2e80-da31-11e9-8461-e6a10c81f94c.png)

So mostly mobile browsers but also some Chrome and Edge on Windows 10.

We're using this babel config:

```es6
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        modules: NODE_ENV === 'test' ? 'auto' : false,
        useBuiltIns: 'entry',
        corejs: 3,
      },
    ],
    '@babel/react',
    '@babel/preset-flow',
  ],
  comments: true,
  plugins: [
    '@babel/transform-runtime',
    '@babel/plugin-transform-flow-strip-types',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-function-bind',

    'lodash',
    'syntax-dynamic-import',

    ...(NODE_ENV === 'test' ? ['dynamic-import-node'] : []),
  ],
}
```

All plugins and presets are the latest versions. 

This is our browser list:

```json
{
  "browserslist": [
    "chrome >= 50",
    "firefox >= 52",
    "safari >= 10",
    "ie >= 11"
  ]
}
```

**The questions**

- Can you either see an obvious error in our configuration? 
- If not, do you have any idea how to pinpoint the error? Maybe you've encountered similar situations before.

**Comment by zloirock** [comment] 2019-10-01 12:02
Something strange. Maybe a conflict with an alternative polyfill. Could you add a reproducible example?

**Comment by johnmarinelli** [comment] 2019-10-02 12:59
I am also getting this bug.  there is a line that mentions a webkit bug in the file: https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/array-buffer-view-core.js#L114 could it be related?

**Comment by zloirock** [comment] 2019-10-02 13:04
@johnmarinelli nope.

**Comment by jonrh** [comment] 2019-10-15 18:27
I have been seeing this same error in production lately. Here is the Rollbar stacktrace I get:

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined

TypeError: undefined
File (native) line (unknown) in setPrototypeOf
File ../node_modules/core-js/internals/array-buffer-view-core.js line 151 col 23 in Object.<anonymous>
if (global[NAME]) setPrototypeOf(global[NAME].prototype, TypedArrayPrototype);

File https://example.com/  line 1 col 27653 in a
File ../node_modules/core-js/internals/array-buffer.js line 7 col 27 in Object.<anonymous>
var NATIVE_ARRAY_BUFFER = require('../internals/array-buffer-view-core').NATIVE_ARRAY_BUFFER;

File https://example.com/  line 1 col 27653 in a
File ../node_modules/core-js/modules/es.array-buffer.constructor.js line 7 col 25 in Object.<anonymous>
var arrayBufferModule = require('../internals/array-buffer');

File https://example.com/  line 1 col 27653 in a
File ../node_modules/react-app-polyfill/stable.js line 95 col 1 in Object.<anonymous>
require("core-js/modules/es.array-buffer.constructor");

File https://example.com/  line 1 col 27653 in a
File https://example.com/static/js/main.f643d182.chunk.js  line 1 col 252 in Object.push.1134
```

I have unfortunately not been able to reproduce the issue. This error originates from a [Create React App](https://github.com/facebook/create-react-app) (v3.1.1) running with [react-app-polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) (v1.0.2).

react-app-polyfill initialisation (as instructed by the CRA docs):

```
// Polyfills create-react-app requires so that the site works in Internet Explorer 11.
import "react-app-polyfill/ie11";

// Polyfill stable JavaScript features
import "react-app-polyfill/stable";
```

Browserlist config in `package.json`:

```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

I'm not sure if this is an issue with core-js, CRA, or react-app-polyfill but this issue matched the closest the error and stacktrace that I have available. Like @frontendphil my traffic seems diverse but it seems to mostly originate from mobile browsers. This happens in about 0.7% of sessions. I am sorry for not being able reproduce and be of more help but I thought I would share some of my details if could potentially help narrow the root of the issue.

**Comment by adam-h** [comment] 2019-10-24 07:06
Seeing the same thing here, without react. In our case it starts at the webpack bootstrap then follows the same stack trace

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
```

```
 File (native) line (unknown) in setPrototypeOf

File webpack:///./node_modules/core-js/internals/array-buffer-view-core.js line 128 col 23 in Object.<anonymous>
if (global[NAME]) setPrototypeOf(global[NAME].prototype, TypedArrayPrototype);

File webpack:///webpack/bootstrap line 89 col 22 in c
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

File webpack:///./node_modules/core-js/internals/array-buffer.js line 4 col 27 in Object.<anonymous>
var NATIVE_ARRAY_BUFFER = require('../internals/array-buffer-view-core').NATIVE_ARRAY_BUFFER;

File webpack:///webpack/bootstrap line 89 col 22 in c
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

File webpack:///./node_modules/core-js/modules/es.array-buffer.constructor.js line 4 col 25 in Object.<anonymous>
var arrayBufferModule = require('../internals/array-buffer');

File webpack:///webpack/bootstrap line 89 col 22 in c
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

**Comment by zloirock** [comment] 2019-10-24 23:34
Still no ideas. A reproducible example could be very useful. Could you add lists of your dependencies? Maybe you load something before `core-js` or it's at the top of your entry point?

**Comment by adam-h** [comment] 2019-10-25 03:24
At the top of my entrypoint is:

```js
import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

The only thing that loads before it is the webpack init stuff.

Deps (all latest as of writing):
```
@babel/core: 7.6.4
@babel/preset-env: 7.6.3
@babel/runtime-corejs3: 7.6.3
core-js: 3.3.3
webpack: 4.41.2
```

Sadly still not able to reproduce at all, and we've not had any customers reporting issues - just errors in our tracker (Rollbar)

**Comment by alpaca-tc** [comment] 2019-11-09 07:45
I have been seeing this same error after updating `core-js@3` from `2`. 🤔

**Comment by brentmulligan** [comment] 2019-11-21 20:30
Also seeing this error in our Rollbar tracker after moving from babel-polyfill to core-js 3. I have not been able to reproduce it.

**Comment by gurgeous** [comment] 2019-12-02 18:57
I am seeing this error as well. Unfortunately our app is complex and a simple test case is probably hard to extract. Sorry about that. This is the #1 error on our dashboard. All Chrome, all Windows.

**Comment by robcole** [comment] 2019-12-05 01:45
We're seeing this in our Sentry tracker as well.

**Comment by jonrh** [comment] 2020-02-14 10:36
I haven't seen this crop up again in about 2 months. All third party dependencies have remained unchanged. I have no clue what could have been causing this.

**Comment by zloirock** [comment] 2021-04-09 14:07
Since still no reproducible example, closed as `can't reproduce`.

**Closed by zloirock** 2021-04-09 14:07 UTC
Labels: can't reproduce
