### ISSUE TITLE
IE11SCRIPT5017: Syntax error in regular expression 

### ISSUE THREAD

**Issue by CubaJas** [zloirock/core-js#650] opened 2019-09-20 14:11 UTC
After windows update KB4516046 there is an error in IE11 in es6.regexp.constructor.js (37, 3)
IE11SCRIPT5017: Syntax error in regular expression 

` for (var keys = gOPN(Base), i = 0; keys.length > i;) proxy(keys[i++]);`

**Comment by zloirock** [comment] 2019-10-01 12:00
It's just a wrapper that doesn't change the pattern, because of this you see this line in the stack trace, so most likely you will have this error even without `core-js`. If you don't think so, please, add a reproducible example or more information.

**Comment by zloirock** [comment] 2019-10-13 15:02
Closed as `can't reproduce`.

**Closed by zloirock** 2019-10-13 15:02 UTC
Labels: can't reproduce
