### ISSUE TITLE
logger not found in es6.promise.js of core-js

### ISSUE THREAD

**Issue by shreychaturvedi123** [zloirock/core-js#109] opened 2015-09-23 11:36 UTC
At line 96 , I did a hack
} catch(err){
if(console){
console.log(err);
}
react.rej(err);
}
but if i use logger.log then it says logger is not defined and i am using winston logger globally and in catch also it is getting error that "logger is not defined".
[ReferenceError: logger is not defined]

**Comment by zloirock** [comment] 2015-09-23 11:38
So... `logger` defined before `core-js`?

**Comment by shreychaturvedi123** [comment] 2015-09-23 11:42
yeah , i have raised this issue in core-js.

**Comment by zloirock** [comment] 2015-09-23 18:17
@shreychaturvedi123 I don't see a reproducible example. Or you already solved this problem?

**Comment by shreychaturvedi123** [comment] 2015-09-24 06:32
I am trying to give a reproducable example, btw where does react.rej(err) goes to.

**Comment by zloirock** [comment] 2015-09-26 11:02
Close this because I don't see a reproducible example.

**Closed by zloirock** 2015-09-26 11:02 UTC
Labels: question
