### ISSUE TITLE
Any thoughts on adding browser Custom Event Polyfills

### ISSUE THREAD

**Issue by dinukadesilva** [zloirock/core-js#401] opened 2018-05-11 19:59 UTC
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by loganfsmyth** [comment] 2018-05-11 20:00
Duplicate of #354

**Comment by dinukadesilva** [comment] 2018-05-11 20:01
Is this not a focus of this project or is it waiting for a contributor. (I would love to be if needed)

**Comment by loganfsmyth** [comment] 2018-05-11 20:02
https://github.com/zloirock/core-js/issues/354#issuecomment-350334898

> At this moment, only ECMAScript and closely related ECMAScript features in the scope of core-js.

**Closed** 2018-05-13 09:03 UTC
Labels: duplicate
