### ISSUE TITLE
Out of stack space in IE11 when trying to add sympol-keyed property to XHR instance

### ISSUE THREAD

**Issue by betalb** [zloirock/core-js#387] opened 2018-03-19 16:15 UTC
Out of stack space in IE11 when trying to add sympol-keyed property to XHR instance

When trying to set some property on XMLHttpRequest instance with Symbol as property key, IE11 throws Out of stack space exception.

Here is simple reproducible test case
```
<script type="text/javascript" src="https://raw.githack.com/zloirock/core-js/v2.5.1/client/shim.min.js"></script>
<script type="text/javascript">
    var ctxSymbol = Symbol('smbl');

    var xhrInstanceUnderTest = new XMLHttpRequest();
    xhrInstanceUnderTest[ctxSymbol] = 'hello';
</script>
```

Error occurs in `core-js/modules/es6.symbol.js` $set (inside of `if (!USE_NATIVE)`) goes into infinite recursion

**Comment by zloirock** [comment] 2018-03-19 17:09
Looks like a duplicate of  #163

**Comment by zloirock** [comment] 2018-03-19 17:16
You can see [a note about possible problems with environment exotic objects in the caveats section of README](https://github.com/zloirock/core-js#caveats-when-using-symbol-polyfill). If you have some ideas how to fix it - feel free to add a PR.

**Closed by zloirock** 2018-03-19 17:16 UTC
