### ISSUE TITLE
Function.isPlainObject fails when using ES6

### ISSUE THREAD

**Issue by gsklee** [zloirock/core-js#34] opened 2015-02-20 03:38 UTC
```
[00:42:29] TypeError: boolean is not a function
    at Function.isPlainObject (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:1652:64)
    at Object.globule.find (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:64:19)
    at Gaze.add (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:174:19)
    at new Gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/kaylee/projects/manic/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/kaylee/projects/manic/gulpfile.babel.js:85:10)
    at module.exports (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

Issue History:
https://github.com/babel/babel/issues/489
https://github.com/wearefractal/glob-watcher/issues/15
https://github.com/lodash/lodash/issues/981

**Comment by zloirock** [comment] 2015-02-20 04:26
I know about this issue. `core-js` wraps `Object.getPrototypeOf` for support primitives, see spec ES6. It's not `core-js` issue. The problem is that old `LoDash` checks that the function is native. It's fixed in actual versions. I can fix it as
```js
Object.getPrototypeOf.toString = function(){
  return 'function getPrototypeOf() { [native code] }'
}
```
but not sure it's realy needed, be better update `LoDash`.

**Closed** 2015-02-20 04:28 UTC
