### ISSUE TITLE
Uncaught TypeError: Array is not a function

### ISSUE THREAD

**Issue by wood1986** [zloirock/core-js#310] opened 2017-06-17 22:07 UTC
After the webpack bundling, it gives me some code like `Array(34)`. And this code is supposed to be es5 compatible. As the original source is coded in es6 syntax and with es6 methods, I did include `core-js/es6` in `webpack.config.js`

if I remove the `core-js/es6` and open my app in Chrome, no errors. Oppositely, if I include `core-js/es6`, it shows an error. Array is overridden by `core-js`

`function Array() { [ native code ] }` get overridden by `core-js`

What do I miss?

**Comment by jaydenseric** [comment] 2017-06-24 14:46
Are you using Webpack v3?

Take a look at https://github.com/webpack/webpack/issues/5135.

**Comment by wood1986** [comment] 2017-06-24 17:24
Webpack 2 has the same issue

**Comment by zloirock** [comment] 2017-07-12 08:41
`core-js` should not replace `Array` constructor. Seems it's not a `core-js` bug. Could you add a reproducible example?

**Comment by zloirock** [comment] 2017-08-06 14:59
Seems a problem of bundler, closed as `can't reproduce`.

**Closed by zloirock** 2017-08-06 14:59 UTC
Labels: can't reproduce
