### ISSUE TITLE
Since V 2.6.7 problem with google maps js and IE11

### ISSUE THREAD

**Issue by ZouhaierSebri** [zloirock/core-js#567] opened 2019-05-30 15:25 UTC
https://maps.googleapis.com/maps/api/js?key=XXXXX

SCRIPT5005: String expected
js (48,286)

"_.ya.Symbol.iterator"

SCRIPT5022: Exception thrown and not caught.
es2015-polyfills.js (3265,3)

**Comment by zloirock** [comment] 2019-05-30 16:02
The problem on google maps side since they override `core-js` `Symbol` polyfill by own polyfill. Duplicate of #566 or https://github.com/babel/babel/issues/9993

**Comment by zloirock** [comment] 2019-05-31 08:33
You can follow the recommendation from #566 - load `core-js` before google maps. More other, loading of polyfills before all the rest code is recommended way how polyfills should be used.

**Closed by zloirock** 2019-05-31 08:33 UTC
Labels: duplicate

**Comment by dcchristopher** [comment] 2019-06-05 14:39
Thanks a lot, Google! This issue brought down a legacy production Angular page (it quit rendering in IE11 only). For anyone else having this issue, I simply updated core-js from 2.5.5 to 2.5.7 and it worked.

**Comment by ZouhaierSebri** [comment] 2019-06-10 10:56
@dcchristopher 
I'm using 2.6.5 to resolve the problem. the issue as described Since V 2.6.7

**Comment by Cobertos** [comment] 2019-07-24 14:58
#566 Seems to be the exact problem I was having causing our IE11 site to break, except the issue is with Google's Recaptcha api.js. Removing it from the project or making it load after your packed bundle fixes IE11. The file in question that I had to move was `//www.google.com/recaptcha/api.js?h1=en&amp;render=explicit`.

The specific IE11 error I was getting was:

SCRIPT5005: String expected in the regenerator-runtime library that seems to extend from this Symbol polyfill conflict.

**Comment by ot-dchristopher** [comment] 2019-07-24 15:09
@Cobertos it's safe to say that various Google APIs will exhibit this issue. For those downvoting solutions that worked for others, feel free to hardcode your polyfill fixes. Some of us would rather just change the version to one where this issue hasn't regressed. We shouldn't have to babysit dependencies.

**Comment by dcchristopher** [comment] 2019-07-24 15:16
@Cobertos it's safe to say that various Google APIs will exhibit this issue. For those downvoting solutions that worked for others, feel free to hardcode your polyfill fixes. Some of us would rather just change the version to one where this issue hasn't regressed. We shouldn't have to babysit dependencies

**Comment by Jossnaz** [comment] 2020-07-29 19:04
was able to fix the problem by pasting
```
    <script src="https://polyfill.io/v3/polyfill.js?features=Symbol%2CObject.getOwnPropertySymbols%2CSymbol.asyncIterator%2CSymbol.for%2CSymbol.hasInstance%2CSymbol.isConcatSpreadable%2CSymbol.iterator%2CSymbol.keyFor%2CSymbol.match%2CSymbol.replace%2CSymbol.prototype.description%2CSymbol.search%2CSymbol.species%2CSymbol.split%2CSymbol.toPrimitive%2CSymbol.toStringTag%2CSymbol.unscopables"></script>

```
right before the recaptcha script as moving the recaptcha script tag below my own scripts wasn't an option (well, at least not one without refactoring code)
