### ISSUE TITLE
IE inline styles missing after Vue loaded

### ISSUE THREAD

**Issue by threeeyedgoose** [zloirock/core-js#862] opened 2020-09-09 20:50 UTC
After updating 3.3.3 to  3.6.5 in IE disappear inline slyles
<div style="background-image: url(banner.png);"></div>
after loading vue becomes 
<div></div>

Console has no errors

**Comment by smilingkite** [comment] 2020-09-23 07:18
We had several IE related issues as well. Bringing core-js back to version 3.3.3 helped. So thanks. 

We also work with vue (babel, webpack, the works).

**Comment by zloirock** [comment] 2020-10-27 08:41
I have no ideas about how it could be related `core-js`. Please, add a reproducible example.

**Comment by japboy** [comment] 2020-12-07 08:08
let me just share that it also happens to me. varied results on same page depends on `core-js` version;

`core-js@3.6.0` | `core-js@3.5.0`
--|--
![image](https://user-images.githubusercontent.com/84360/101324063-f8861800-38ac-11eb-948f-ebeb905681fb.png) | ![image](https://user-images.githubusercontent.com/84360/101324655-efe21180-38ad-11eb-8b3e-bf317fa9772e.png)

like @smilingkite says, html class names somehow got spaces between the letters and that causes visual regressions.

i have my build configuration based on `webpack@4`, babel, postcss, & `vue@2`. i also shares same babel, postcss configuration with `nuxt@2` though it only happens on the former sertup.

i havent found any details though. i might find the detail or not... 🙏

**Comment by zloirock** [comment] 2021-04-07 18:38
Closed as `can't reproduce`.

**Closed by zloirock** 2021-04-07 18:38 UTC
Labels: can't reproduce
