### ISSUE TITLE
Fix RangeError: Maximum Call Stack Size Exceeded in inspect-source.js with Hermes JS Engine in core-js versions 3.39.0

### ISSUE THREAD

**Issue by RoshanSharma8245** [zloirock/core-js#1381] opened 2024-11-26 12:24 UTC
I'm encountering a RangeError: Maximum call stack size exceeded (native stack depth) error while using the Hermes JavaScript engine. The issue originates from inspect-source.js in core-js versions 3.39.0. The problematic code is as follows:
```javascript
var functionToString = uncurryThis(Function.toString);

// this helper broken in `core-js@3.4.1-3.4.4`, so we can't use `shared` helper
if (!isCallable(store.inspectSource)) {
  store.inspectSource = function (it) {
    return functionToString(it);
  };
}
``` 

The error appears to stem from improper handling of recursion in store.inspectSource. 
**Proposed Solution:**
Below is a suggested fix that resolves the issue by adding safeguards:
```javascript
var functionToString = uncurryThis(Function.prototype.toString);

// Avoid recursion in `store.inspectSource`
if (!isCallable(store.inspectSource)) {
  store.inspectSource = function (it) {
    try {
      return isCallable(it) ? functionToString(it) : '';
    } catch (error) {
      // Fallback to an empty string if `functionToString` fails
      return '';
    }
  };
}
``` 
The changes include:

1. Correcting Function.toString to Function.prototype.toString.
2. Adding a try-catch block to prevent crashes in case functionToString fails.
3. Adding a fallback return value for non-callable inputs.

Please consider this fix to prevent similar issues in the future.

**Comment by irajdubey** [comment] 2024-11-26 12:26
Facing the same issue.

**Comment by zloirock** [comment] 2024-11-26 13:50
This logic was not changed in 3.39.0. It was not changed for a long time.

It's just a demetodized version of `Function#toString`.

It should throw a error for non-callable object.

A `RangeError` here could show problems with a transpiling - for example, you forget to exclude `core-js` in Babel / SWC settings.

Could you add a reproducible example?

**Comment by zloirock** [comment] 2024-11-26 14:00
I don't run the full test case in Hermes, however I just run full `core-js` bundle with some simple test in Hermes and it works fine. So waiting for a reproducible example.

**Comment by d-kemenau** [comment] 2024-11-29 15:38
text🇱🇺 text

**Comment by zloirock** [comment] 2024-12-02 18:00
Any news with a reproducible example?

**Comment by Vyazovoy** [comment] 2024-12-16 18:34
This issue is likely caused by the same dynamic inline requires settings as was mentioned by https://github.com/zloirock/core-js/issues/1237

**Comment by zloirock** [comment] 2024-12-23 18:54
It seems @Vyazovoy is correct, it's an issue of your build process. Closed as `can't reproduce`. Please, add a reproducible example if you don't agree.

**Closed by zloirock** 2024-12-23 18:54 UTC
Labels: can't reproduce
