### ISSUE TITLE
Promise polyfill on core-js 3 breaks Vue nextTick (using microtasks) on Tizen 2016

### ISSUE THREAD

**Issue by victortwc** [zloirock/core-js#814] opened 2020-04-18 12:06 UTC
Hello!

It's a super weird edge case that works fine on core-js@2 but breaks on core-js@3. While investigating, I could narrow down to the promise polyfill, by including every polyfill from core-js@3 except Promise, which I included core-js@2 instead, the app works fine.

My use case is described in this issue:
https://github.com/vuejs/vue-cli/issues/5386

TV User agent:
"Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1"

Vue nextTick implementation:
https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js#L13

Even though this function is tied to this:
```
const p = Promise.resolve()
  
timerFunc = () => {
    p.then(flushCallbacks)
    if (isIOS) setTimeout(noop)
}
```
it will only get executed if another task is queued, like a setTimeout. If I wrap my events in a setTimeout it works again, but it looks like a dirty hack.

Are there any fundamental differences between the v2 and v3 Promise/microtask polyfills? Hope this helps to solve the mystery.

I'm also thinking of sending a PR to Vue to add `if (isIOS || isTizen)` to that condition, but if it can be solved on the core-js level probably more people would benefit.

**Comment by slowcheetah** [comment] 2020-04-22 09:45
@victortwc In the nextTick implementation, I see a problem in that there is a hack for iOS already. The call is made from iOS, but the implementation does not define this system as iOS.

I will try to look at this problem in general

**Comment by victortwc** [comment] 2020-04-22 11:13
Thanks @slowcheetah! The hack is to force the queue to process jobs by pushing a setTimeout there, which, while works for Tizen, I can imagine that if it was working on core-js v2 something weird is going on and also using microtasks would have a much better performance than `setTimeout`.

Our use-case is a video player, so performance is important as in frequent updates would cause UI lags and so on. TV devices are capped in hardware, so very important to keep performance in mind. For now we will be using core-js@2 because that works. I'm just connecting the teams here because this issue might cause other bugs somewhere else as well.

**Comment by slowcheetah** [comment] 2020-04-26 16:08
I tried to figure it out, but without a reproducible example (which is not so easy to do due to the exotic environment) I did not succeed. The difference between version 2 and 3 is huge, so I can’t even imagine what might cause this problem.

**Comment by victortwc** [comment] 2020-04-26 20:36
@slowcheetah thanks for the response. Would you be willing to investigate if I put up an example with this? Tizen supports an emulator which is free to use and has remote debugging capabilities.

**Comment by slowcheetah** [comment] 2020-05-06 04:15
@victortwc sorry for long answer. Can you give a working example of a Tizen definition? I think that then it is necessary to teach core-js to define this environment.

**Comment by zloirock** [comment] 2020-11-06 15:17
Could you check it with the actual version? The priority of microtask implementations was changed.

**Comment by zloirock** [comment] 2021-04-07 18:51
Closed as `can't reproduce`.

**Closed by zloirock** 2021-04-07 18:51 UTC
Labels: can't reproduce, exotic environment, help wanted
