### ISSUE TITLE
core-js/es6/promise IE 9 Error

### ISSUE THREAD

**Issue by Galphimbl** [zloirock/core-js#328] opened 2017-08-18 15:45 UTC
Promise has method catch, that can't be used in IE9, becouse IE think that varName.catch() is native catch(Error) {} and throw Error

**Comment by zloirock** [comment] 2017-08-19 05:50
Duplicate of #294.

**Closed by zloirock** 2017-08-19 05:50 UTC

**Comment by zloirock** [comment] 2017-08-19 05:52
Also, IIRC, it's a problem only for IE8-, not for IE9.
