### ISSUE TITLE
postinstall not found issue during npm install

### ISSUE THREAD

**Issue by scalebig** [zloirock/core-js#557] opened 2019-05-21 19:22 UTC
![image](https://user-images.githubusercontent.com/6069355/58124165-2c1e2600-7bd3-11e9-864e-b742ecb9ca7d.png)

dependency of `sequelize-cli` version: 4.0.0
node version: 10.15.3
npm version: 6.4.1

this happens while sequelize-cli is npm installing in our alpine container build via Google Container Builder. This build has worked repeated until today :(

**Comment by zloirock** [comment] 2019-05-21 19:28
Seems a duplicate of #551

**Closed by zloirock** 2019-05-21 19:28 UTC

**Comment by scalebig** [comment] 2019-05-21 20:02
Sorry about that!
