### ISSUE TITLE
Issue with wkhtmltopdf (webkit version = ~Safari 5) after fcbc2c878535

### ISSUE THREAD

**Issue by terencehonles** [zloirock/core-js#1009] opened 2021-11-19 09:03 UTC
Hi, I am seeing an issue with my application when building against core-js 3.19.x and I resolved this by downgrading to the 3.18.3 release. Specifically this looks like it's related to fcbc2c878535. My test case is using wkhtmltopdf, which is built with Qt and has an old version of webkit that is missing a few things.

I polyfill `Function.prototype.bind` manually since webpack uses it before I've loaded core-js, and I've also tried forcing core-js to override the polyfill in case the core-js version behaved differently / better.

The problem is that I'm getting a call stack size exceeded error, and this happens when patching `es.array.copy-within.js`. When exporting the polyfill, specifically when redefining the target, `hasOwn` is called with `(<copyWithin()>, 'name')` which causes the error.

While debugging I changed the definition of `function-uncurry-this.js` to not use `callBind` but instead the other side of the ternary expression:

```javascript
function (fn) {
  return fn && function () {
    return call.apply(fn, arguments);
  };
};
```

This removed the error I was seeing. I'm not sure why `function-uncurry-this.js` is so specialized. I previously wasn't aware why you'd be calling `bind` on a function (for `callBind`), but I see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind#creating_shortcuts.  Is there a significantly measureable difference by using:

```javascript
function (fn) {
  return fn && callBind(call, fn);
}
```

Or can we simplify the code to use the other side of the termary expression?

When debugging what this was doing in chrome it looked like `hasOwnProperty` was the native version, but because there was a call stack issue I assume in wkhtmltopdf it is wrapped somehow (this is likely because `bind` is being polyfilled).

Anyways, hopefully this information is useful and I can provide more details as needed.

**Comment by zloirock** [comment] 2021-11-19 11:31
Hi @terencehonles. Unfortunately, we can't avoid `.bind` in `uncurryThis` if it's available since the main reason for this change is avoiding a way to break or observe `core-js` internals by patching built-ins. For example,
```js
Function.prototype.apply = function (that, args) {
  console.log('apply');
  return Reflect.apply(this, that, args);
}
```
I don't see something in `uncurryThis` that can be broken by a proper `.bind` polyfill, so I think that you should find the issue in this polyfill or in your bundling process, without the additional info or a reproducible example I can't help here.

**Comment by terencehonles** [comment] 2021-11-19 15:59
I see, I'm not sure why leaking the internals is particularly important, but that's not particularly important.

For now we can work with the legacy `core-js` version, but I'll try to spend some time looking into why this is an issue. In the long term regardless we'd like to move to a better and more supported rendering engine for PDF generation so we may also look at that instead. I'll follow up with anything I find, I just wanted to leave a note of my issue so I didn't forget and so others may be able to find it also.

**Comment by zloirock** [comment] 2021-11-19 18:25
Since it's an issue of third-party polyfill or a building process, I'm closing this issue. If you will provide a reproducible example or additional info, I'll try to help you.

**Closed by zloirock** 2021-11-19 18:25 UTC
