### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by tinyesp** [zloirock/core-js#323] opened 2017-07-31 15:49 UTC
I am having a strange error when using core-js in typescript, not sure the cause yet...

Error: Cannot convert object to primitive value
  Evaluating npm:core-js@2.4.0/modules/es6.promise.js
  Evaluating npm:core-js@2.4.0/shim.js
  Evaluating npm:core-js@2.4.0/index.js
  Evaluating http://localhost:9000/assets/javascripts/src/ts/main.ts
  Loading src/ts/main
    at dependencies.js:67646
    at S (system.js:4)
    at E (system.js:4)
    at k (system.js:4)
    at system.js:4
    at dependencies.js:71262
    at S (system.js:4)
    at E (system.js:4)
    at k (system.js:4)
    at system.js:4

**Comment by zloirock** [comment] 2017-08-01 16:10
Could you add a reproducible example?

**Comment by zloirock** [comment] 2017-08-07 05:49
Closed as `can't reproduce`.

**Closed by zloirock** 2017-08-07 05:49 UTC
Labels: can't reproduce
