### ISSUE TITLE
RegExp polyfill path may be triggering on new V8 versions

### ISSUE THREAD

**Issue by littledan** [zloirock/core-js#306] opened 2017-05-28 09:08 UTC
Ideally, core.js should either feature-detect that V8 implements ES2015 RegExp semantics and therefore leave RegExp alone, or V8 should fix itself so that it does implement those semantics. However, @schuay reports at https://github.com/babel/babel/issues/5771 that V8 triggers core.js to modify RegExp.

**Comment by zloirock** [comment] 2018-03-25 12:05
As I already wrote, I was not able to reproduce this issue. Here is a feature detection:

```js
var re1 = /a/g;
var re2 = /a/g;
re2[Symbol.match] = false;
RegExp(re1) == re1 && RegExp(re2) != re2 && RegExp(re1, 'i') == '/a/i';
```

`RegExp` constructor (and `RegExp.prototype.constructor`) polyfilled only in case if it's failed, but V8 passes it for a long time.

But now we have one more issue. In the article I see the note:

> To take the fast path:
> - `regexp` must be unmodified (no added, deleted, or modified properties)
> - `regexp.prototype` must be unmodified
> - `regexp.lastIndex` must be a simple non-negative integer — not an object, not a getter.

Disallowing modification of `RegExp.prototype` is disallowing polyfilling of `RegExp`-related features. The first example - updated algorithm of `String#matchAll` which should use `RegExp#@@matchAll` method. So what we should do in this case?

**Comment by zloirock** [comment] 2019-06-25 08:59
Seems related https://bugs.chromium.org/p/chromium/issues/detail?id=977382

**Comment by schuay** [comment] 2019-06-26 06:59
https://crbug.com/977382 is also related to regexp fast paths, but probably not relevant to this issue.

Things have gotten a *bit* better than when this issue was originally opened. It is now possible to modify existing but irrelevant functions on the prototype without falling off the fast path (e.g.: String.prototype.match only checks @@match and exec).

Unfortunately, adding a new property to the prototype will still trigger the slow path.

On your side, there's not much you can do except be conservative about modifying the regexp prototype.

On the V8 side, the goal is still to switch to a smarter fast path check that only checks relevant properties, ignoring all other changes on the prototype. The relevant V8 bug is https://crbug.com/v8/5577.

**Comment by danielhusar** [comment] 2019-06-27 02:58
Hey guys, I think I have repro case for this issue: (thanks to @rickharrison)

repository: https://github.com/danielhusar/core-js-performance
demo: https://core-js-preformance.netlify.com/

Follow the steps in the demo link.

**Comment by schuay** [comment] 2019-06-27 04:52
> Hey guys, I think I have repro case for this issue

Indeed. The slowdown even persists beyond page reload within the same tab.

**Comment by danielhusar** [comment] 2019-06-27 15:46
The scary part is that you can include this polyfill even in iframe, and your whole tab (parent window, etc..) will get slow paths, probably forever.

**Comment by schuay** [comment] 2019-07-01 13:01
I hope to look into a fix for this soon (definitely the cross-context leak of state, perhaps also a more permissive fast path check).

**Comment by schuay** [comment] 2019-07-11 08:20
https://crrev.com/c/1695465 should fix the cross-navigation and page-reload pollution for the example above (https://core-js-preformance.netlify.com/).

**Comment by schuay** [comment] 2019-07-29 09:55
And https://crrev.com/c/1706056 allows benign changes to the `RegExp` prototype on the fast path. Currently limited to a subset of regexp builtins, but can be extended to all builtins with a bit of work.

**Comment by ecc521** [comment] 2019-10-02 01:22
I'm also noticing extreme RegExp performance problems - after including core-js, performance of searching plunged 120x, and my whole application ground to a halt.

Doing some testing, I measured about 1/3rd of a millisecond to split a 20 character string using the really simple regexp ```/[, ]+/``` - That's just **_sad_**.

There doesn't appear to be much progress on the V8 side. I'm slightly surprised by this, especially given just how slow the slow path is - it is quite possible that a fix have a small but noticeable performance improvement across the board. It would be interesting to see some statistics on how often people use regexps.

Is there any reason that core-js needs to modify the RegExp prototype in more recent versions of V8? I may well be missing something, but V8 tends to keep up with the standards game relatively well.

**Comment by schuay** [comment] 2019-10-02 05:46
> I'd also like to ask: Is there any reason that core-js needs to modify the RegExp prototype in more recent versions of V8? I'm probably missing something, but V8 tends to keep up with the standards game relatively well.

+1 that is my question as well. If there is any way to avoid it, one should not touch builtin prototypes.

> There doesn't appear to be much progress on the V8 side, which is a little surprising given just how slow the slow path is. I'll see if I can do anything there.

There is no work planned to speed up the slow path. The assumption we are operating on is that if you fall off the fast path, you're out of luck. Results are still correct, but performance will likely be unimpressive.

We do have ideas on how to rewrite RegExp builtins to widen the fast path further, but that would be a larger project. At the moment, I don't see it happening any time soon. Pragmatically, I think the best way to proceed is to work with core-js and figure out if modifying the prototype is necessary at all.

**Comment by ecc521** [comment] 2019-10-02 14:46
I'm seeing the modification happening in fix_re_wks.js, with the code:
```
var SPLIT_WORKS_WITH_OVERWRITTEN_EXEC = (function () {
  // Chrome 51 has a buggy "split" implementation when RegExp#exec !== nativeExec
  var re = /(?:)/;
  var originalExec = re.exec;
  re.exec = function () { return originalExec.apply(this, arguments); };
  var result = 'ab'.split(re);
  return result.length === 2 && result[0] === 'a' && result[1] === 'b';
})();
```
If this is Chrome 51 only, we should be able to easily fix it - I would personally be willing to resort to useragent sniffing if absolutely necessary.

**Comment by zloirock** [comment] 2019-10-24 00:57
https://github.com/zloirock/core-js/issues/677 one more problem like that.

**Comment by ecc521** [comment] 2019-10-24 01:35
100x is a lot closer to the slowdown that I was seeing on ```Array.prototype.slice```.
Usage counters have been added to the [V8 bug report](https://bugs.chromium.org/p/v8/issues/detail?id=5577#c31), so some progress may happen in the future.

**Comment by zloirock** [comment] 2019-10-24 18:13
The main performance problem here caused by the same code as in #677 - [`@@species` support detection](https://github.com/zloirock/core-js/blob/v3.3.3/packages/core-js/internals/fix-regexp-well-known-symbol-logic.js#L43-L58).

**Comment by zloirock** [comment] 2019-10-24 18:49
Could you check this patch on your cases? On my simple test case, it works fine.

**Comment by ecc521** [comment] 2019-10-25 01:38
Since I haven't messed with Core-JS before, testing this was a mess (first tried to install on an ARM laptop, then all the can't resolve module issues, etc)
**I am seeing a 114x performance improvement though. It looks like this fixes it.**

**Comment by zloirock** [comment] 2019-10-25 22:29
@schuay what about your test case?

**Closed** 2019-10-27 22:37 UTC
Labels: compatibility, help wanted, v8

**Comment by zloirock** [comment] 2019-10-27 22:40
Adding any new `RegExp`-related polyfill will cause this issue again since it's a modification of `RegExp.prototype`, so **it should be fixed on V8 side**. Waiting for this fix or a new `RegExp`-related proposal.

**Comment by schuay** [comment] 2019-10-28 07:50
> @schuay what about your test case?

I lost context here, which test case do you mean?

> Adding any new RegExp-related polyfill will cause this issue again since it's a modification of RegExp.prototype, so it should be fixed on V8 side. Waiting for this fix or a new RegExp-related proposal.

If possible, we should fix the current issue first and worry about future changes when they come.

**Comment by zloirock** [comment] 2019-10-28 08:16
> I lost context here, which test case do you mean?

Which initially was a reason for this issue?

**Comment by schuay** [comment] 2019-10-28 08:34
> > I lost context here, which test case do you mean?
> Which initially was a reason for this issue?

Well, multiple loosely-related things have been discussed on this issue so far ;)

The original bug report was apparently for the `es6.regexp.constructor` polyfill. I don't think the fix in https://github.com/zloirock/core-js/commit/a9aef3c1cc63a722fd69f134804e0af0d2430ca8 will affect the logic in https://github.com/zloirock/core-js/blob/8714aecf822eb1b361c7a76a69a77e8862fe5993/packages/core-js/modules/es.regexp.constructor.js.

I'm not sure the original issue is still valid as you've mentioned previously. The associated feature detection seems to work fine on a current V8:

https://github.com/zloirock/core-js/blob/8714aecf822eb1b361c7a76a69a77e8862fe5993/packages/core-js/modules/es.regexp.constructor.js#L26

```
V8 version 8.0.0 (candidate)
d8> const re1 = /a/g
d8> const re2 = /a/g
d8> re2[Symbol.match] = false;
d8> RegExp(re1) != re1
false
d8> RegExp(re2) == re2
false
d8> RegExp(re1, 'i') != '/a/i'
false
```
