### ISSUE TITLE
infinite window reload when using Promise

### ISSUE THREAD

**Issue by mghelichkhani** [zloirock/core-js#627] opened 2019-08-23 07:38 UTC
I want to run the following piece of code on IE11
```javascript
let myPromise = Promise.resolve(123);
myPromise.then((value) => { 
console.log(value);
});
```
My recipe is Rollup and babel with the following `.babelrc` configuration:
```javascript
{
    "presets": [
        ["@babel/preset-env", {
            "useBuiltIns": "usage",
            "corejs": 3,
            "targets": {
                "browsers": ["last 2 versions", "ie >= 11"]
            }
        }]
     ]
}
```
When I try to load the code, I get some infinite loop. The browser's tab seems to reload every couple of milliseconds.

**Comment by zloirock** [comment] 2019-08-23 11:07
Make sure that `babel` does not transform `core-js`.

**Comment by zloirock** [comment] 2019-08-25 10:51
Did you check it?

**Comment by mghelichkhani** [comment] 2019-08-25 17:32
Thanks for the reply. Could you be more specific?
In case it helps you, this is how our gulp uses babel.
```javascript
rollup({ plugins: [babel(), resolve(), commonjs() ] }, { format: 'cjs', strict: false })
```

**Comment by zloirock** [comment] 2019-08-25 17:36
You should exclude `core-js` from `babel` transform.

**Comment by mghelichkhani** [comment] 2019-08-25 17:45
Excluding `node_modules` didn't help :(
```javascript
.pipe(rollup({ plugins: [babel({exclude: 'node_modules/**'}), resolve(), commonjs() ] }, { format: 'cjs', strict: false }))```

**Comment by zloirock** [comment] 2019-08-25 17:49
The same result - infinite reloading? I have no ideas. Please, create a reproducible example.

**Comment by mghelichkhani** [comment] 2019-08-25 17:52
May be babel doesn't respect my `exclude` phrase.
Let me try it a bit more tomorrow. If i didn't succeed, I will get back to you with the example.

**Comment by mghelichkhani** [comment] 2019-08-26 14:12
@zloirock I created an example here: https://github.com/mghelichkhani/gulp-rollup-seed
`npm install` and `gulp build:scripts:babel` should do the job
then it doesn't matter in what browser you open it. It always goes into the loop.

**Comment by zloirock** [comment] 2019-08-26 18:40
It's a duplicate of #587. It's `rollup`, not `core-js`, bug.

**Closed by zloirock** 2019-08-26 18:40 UTC

**Comment by zloirock** [comment] 2019-08-26 18:45
You could change options to `format: 'iife'` to make it work.
